/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the IntraService5SettingsApiModelsBaseNamedModel10D7 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntraService5SettingsApiModelsBaseNamedModel10D7{}

// IntraService5SettingsApiModelsBaseNamedModel10D7 struct for IntraService5SettingsApiModelsBaseNamedModel10D7
type IntraService5SettingsApiModelsBaseNamedModel10D7 struct {
	Id NullableInt64 `json:"id,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	Name NullableString `json:"name,omitempty"`
	SortOrder NullableString `json:"sortOrder,omitempty"`
	Description NullableString `json:"description,omitempty"`
	IsArchived NullableBool `json:"isArchived,omitempty"`
	SearchString NullableString `json:"searchString,omitempty"`
}

// NewIntraService5SettingsApiModelsBaseNamedModel10D7 instantiates a new IntraService5SettingsApiModelsBaseNamedModel10D7 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntraService5SettingsApiModelsBaseNamedModel10D7() *IntraService5SettingsApiModelsBaseNamedModel10D7 {
	this := IntraService5SettingsApiModelsBaseNamedModel10D7{}
	return &this
}

// NewIntraService5SettingsApiModelsBaseNamedModel10D7WithDefaults instantiates a new IntraService5SettingsApiModelsBaseNamedModel10D7 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntraService5SettingsApiModelsBaseNamedModel10D7WithDefaults() *IntraService5SettingsApiModelsBaseNamedModel10D7 {
	this := IntraService5SettingsApiModelsBaseNamedModel10D7{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) GetId() int64 {
	if o == nil || IsNil(o.Id.Get()) {
		var ret int64
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableInt64 and assigns it to the Id field.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) SetId(v int64) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) UnsetId() {
	o.Id.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) UnsetName() {
	o.Name.Unset()
}

// GetSortOrder returns the SortOrder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) GetSortOrder() string {
	if o == nil || IsNil(o.SortOrder.Get()) {
		var ret string
		return ret
	}
	return *o.SortOrder.Get()
}

// GetSortOrderOk returns a tuple with the SortOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) GetSortOrderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SortOrder.Get(), o.SortOrder.IsSet()
}

// HasSortOrder returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) HasSortOrder() bool {
	if o != nil && o.SortOrder.IsSet() {
		return true
	}

	return false
}

// SetSortOrder gets a reference to the given NullableString and assigns it to the SortOrder field.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) SetSortOrder(v string) {
	o.SortOrder.Set(&v)
}
// SetSortOrderNil sets the value for SortOrder to be an explicit nil
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) SetSortOrderNil() {
	o.SortOrder.Set(nil)
}

// UnsetSortOrder ensures that no value is present for SortOrder, not even an explicit nil
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) UnsetSortOrder() {
	o.SortOrder.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) UnsetDescription() {
	o.Description.Unset()
}

// GetIsArchived returns the IsArchived field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) GetIsArchived() bool {
	if o == nil || IsNil(o.IsArchived.Get()) {
		var ret bool
		return ret
	}
	return *o.IsArchived.Get()
}

// GetIsArchivedOk returns a tuple with the IsArchived field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) GetIsArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsArchived.Get(), o.IsArchived.IsSet()
}

// HasIsArchived returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) HasIsArchived() bool {
	if o != nil && o.IsArchived.IsSet() {
		return true
	}

	return false
}

// SetIsArchived gets a reference to the given NullableBool and assigns it to the IsArchived field.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) SetIsArchived(v bool) {
	o.IsArchived.Set(&v)
}
// SetIsArchivedNil sets the value for IsArchived to be an explicit nil
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) SetIsArchivedNil() {
	o.IsArchived.Set(nil)
}

// UnsetIsArchived ensures that no value is present for IsArchived, not even an explicit nil
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) UnsetIsArchived() {
	o.IsArchived.Unset()
}

// GetSearchString returns the SearchString field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) GetSearchString() string {
	if o == nil || IsNil(o.SearchString.Get()) {
		var ret string
		return ret
	}
	return *o.SearchString.Get()
}

// GetSearchStringOk returns a tuple with the SearchString field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) GetSearchStringOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SearchString.Get(), o.SearchString.IsSet()
}

// HasSearchString returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) HasSearchString() bool {
	if o != nil && o.SearchString.IsSet() {
		return true
	}

	return false
}

// SetSearchString gets a reference to the given NullableString and assigns it to the SearchString field.
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) SetSearchString(v string) {
	o.SearchString.Set(&v)
}
// SetSearchStringNil sets the value for SearchString to be an explicit nil
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) SetSearchStringNil() {
	o.SearchString.Set(nil)
}

// UnsetSearchString ensures that no value is present for SearchString, not even an explicit nil
func (o *IntraService5SettingsApiModelsBaseNamedModel10D7) UnsetSearchString() {
	o.SearchString.Unset()
}

func (o IntraService5SettingsApiModelsBaseNamedModel10D7) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntraService5SettingsApiModelsBaseNamedModel10D7) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.SortOrder.IsSet() {
		toSerialize["sortOrder"] = o.SortOrder.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.IsArchived.IsSet() {
		toSerialize["isArchived"] = o.IsArchived.Get()
	}
	if o.SearchString.IsSet() {
		toSerialize["searchString"] = o.SearchString.Get()
	}
	return toSerialize, nil
}

type NullableIntraService5SettingsApiModelsBaseNamedModel10D7 struct {
	value *IntraService5SettingsApiModelsBaseNamedModel10D7
	isSet bool
}

func (v NullableIntraService5SettingsApiModelsBaseNamedModel10D7) Get() *IntraService5SettingsApiModelsBaseNamedModel10D7 {
	return v.value
}

func (v *NullableIntraService5SettingsApiModelsBaseNamedModel10D7) Set(val *IntraService5SettingsApiModelsBaseNamedModel10D7) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5SettingsApiModelsBaseNamedModel10D7) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5SettingsApiModelsBaseNamedModel10D7) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5SettingsApiModelsBaseNamedModel10D7(val *IntraService5SettingsApiModelsBaseNamedModel10D7) *NullableIntraService5SettingsApiModelsBaseNamedModel10D7 {
	return &NullableIntraService5SettingsApiModelsBaseNamedModel10D7{value: val, isSet: true}
}

func (v NullableIntraService5SettingsApiModelsBaseNamedModel10D7) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5SettingsApiModelsBaseNamedModel10D7) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


