/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IntraService5CommonModelsMailAddress3450 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntraService5CommonModelsMailAddress3450{}

// IntraService5CommonModelsMailAddress3450 struct for IntraService5CommonModelsMailAddress3450
type IntraService5CommonModelsMailAddress3450 struct {
	Name NullableString `json:"name,omitempty"`
	Address NullableString `json:"address,omitempty"`
}

// NewIntraService5CommonModelsMailAddress3450 instantiates a new IntraService5CommonModelsMailAddress3450 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntraService5CommonModelsMailAddress3450() *IntraService5CommonModelsMailAddress3450 {
	this := IntraService5CommonModelsMailAddress3450{}
	return &this
}

// NewIntraService5CommonModelsMailAddress3450WithDefaults instantiates a new IntraService5CommonModelsMailAddress3450 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntraService5CommonModelsMailAddress3450WithDefaults() *IntraService5CommonModelsMailAddress3450 {
	this := IntraService5CommonModelsMailAddress3450{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5CommonModelsMailAddress3450) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5CommonModelsMailAddress3450) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *IntraService5CommonModelsMailAddress3450) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *IntraService5CommonModelsMailAddress3450) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *IntraService5CommonModelsMailAddress3450) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *IntraService5CommonModelsMailAddress3450) UnsetName() {
	o.Name.Unset()
}

// GetAddress returns the Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5CommonModelsMailAddress3450) GetAddress() string {
	if o == nil || IsNil(o.Address.Get()) {
		var ret string
		return ret
	}
	return *o.Address.Get()
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5CommonModelsMailAddress3450) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address.Get(), o.Address.IsSet()
}

// HasAddress returns a boolean if a field has been set.
func (o *IntraService5CommonModelsMailAddress3450) HasAddress() bool {
	if o != nil && o.Address.IsSet() {
		return true
	}

	return false
}

// SetAddress gets a reference to the given NullableString and assigns it to the Address field.
func (o *IntraService5CommonModelsMailAddress3450) SetAddress(v string) {
	o.Address.Set(&v)
}
// SetAddressNil sets the value for Address to be an explicit nil
func (o *IntraService5CommonModelsMailAddress3450) SetAddressNil() {
	o.Address.Set(nil)
}

// UnsetAddress ensures that no value is present for Address, not even an explicit nil
func (o *IntraService5CommonModelsMailAddress3450) UnsetAddress() {
	o.Address.Unset()
}

func (o IntraService5CommonModelsMailAddress3450) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntraService5CommonModelsMailAddress3450) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Address.IsSet() {
		toSerialize["address"] = o.Address.Get()
	}
	return toSerialize, nil
}

type NullableIntraService5CommonModelsMailAddress3450 struct {
	value *IntraService5CommonModelsMailAddress3450
	isSet bool
}

func (v NullableIntraService5CommonModelsMailAddress3450) Get() *IntraService5CommonModelsMailAddress3450 {
	return v.value
}

func (v *NullableIntraService5CommonModelsMailAddress3450) Set(val *IntraService5CommonModelsMailAddress3450) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5CommonModelsMailAddress3450) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5CommonModelsMailAddress3450) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5CommonModelsMailAddress3450(val *IntraService5CommonModelsMailAddress3450) *NullableIntraService5CommonModelsMailAddress3450 {
	return &NullableIntraService5CommonModelsMailAddress3450{value: val, isSet: true}
}

func (v NullableIntraService5CommonModelsMailAddress3450) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5CommonModelsMailAddress3450) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


