/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IntraService5SettingsApiModelsInitClientUserInputModelE478 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntraService5SettingsApiModelsInitClientUserInputModelE478{}

// IntraService5SettingsApiModelsInitClientUserInputModelE478 struct for IntraService5SettingsApiModelsInitClientUserInputModelE478
type IntraService5SettingsApiModelsInitClientUserInputModelE478 struct {
	InitClientUserChannel *IntraService5SharedEnumsInitClientUserChannel342B `json:"initClientUserChannel,omitempty"`
	EmailAddress NullableString `json:"emailAddress,omitempty"`
	EmailAddressObserverList []IntraService5CommonModelsMailAddress3450 `json:"emailAddressObserverList,omitempty"`
	PhoneNumber NullableString `json:"phoneNumber,omitempty"`
	TelegramId NullableInt64 `json:"telegramId,omitempty"`
	TelegramUserName NullableString `json:"telegramUserName,omitempty"`
	WebChatId NullableString `json:"webChatId,omitempty"`
	UserFirstName NullableString `json:"userFirstName,omitempty"`
	UserLastName NullableString `json:"userLastName,omitempty"`
	UserMiddleName NullableString `json:"userMiddleName,omitempty"`
	IsSelfRegistrationConsider *bool `json:"isSelfRegistrationConsider,omitempty"`
	FieldIdValues []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 `json:"fieldIdValues,omitempty"`
	Password NullableString `json:"password,omitempty"`
	ClientType *IntraService5SharedEnumsClientType6CE9 `json:"clientType,omitempty"`
	TaxpayerNumber NullableString `json:"taxpayerNumber,omitempty"`
	Web NullableString `json:"web,omitempty"`
	ClientName NullableString `json:"clientName,omitempty"`
	FieldValues []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9 `json:"fieldValues,omitempty"`
}

// NewIntraService5SettingsApiModelsInitClientUserInputModelE478 instantiates a new IntraService5SettingsApiModelsInitClientUserInputModelE478 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntraService5SettingsApiModelsInitClientUserInputModelE478() *IntraService5SettingsApiModelsInitClientUserInputModelE478 {
	this := IntraService5SettingsApiModelsInitClientUserInputModelE478{}
	return &this
}

// NewIntraService5SettingsApiModelsInitClientUserInputModelE478WithDefaults instantiates a new IntraService5SettingsApiModelsInitClientUserInputModelE478 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntraService5SettingsApiModelsInitClientUserInputModelE478WithDefaults() *IntraService5SettingsApiModelsInitClientUserInputModelE478 {
	this := IntraService5SettingsApiModelsInitClientUserInputModelE478{}
	return &this
}

// GetInitClientUserChannel returns the InitClientUserChannel field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetInitClientUserChannel() IntraService5SharedEnumsInitClientUserChannel342B {
	if o == nil || IsNil(o.InitClientUserChannel) {
		var ret IntraService5SharedEnumsInitClientUserChannel342B
		return ret
	}
	return *o.InitClientUserChannel
}

// GetInitClientUserChannelOk returns a tuple with the InitClientUserChannel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetInitClientUserChannelOk() (*IntraService5SharedEnumsInitClientUserChannel342B, bool) {
	if o == nil || IsNil(o.InitClientUserChannel) {
		return nil, false
	}
	return o.InitClientUserChannel, true
}

// HasInitClientUserChannel returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasInitClientUserChannel() bool {
	if o != nil && !IsNil(o.InitClientUserChannel) {
		return true
	}

	return false
}

// SetInitClientUserChannel gets a reference to the given IntraService5SharedEnumsInitClientUserChannel342B and assigns it to the InitClientUserChannel field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetInitClientUserChannel(v IntraService5SharedEnumsInitClientUserChannel342B) {
	o.InitClientUserChannel = &v
}

// GetEmailAddress returns the EmailAddress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetEmailAddress() string {
	if o == nil || IsNil(o.EmailAddress.Get()) {
		var ret string
		return ret
	}
	return *o.EmailAddress.Get()
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetEmailAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EmailAddress.Get(), o.EmailAddress.IsSet()
}

// HasEmailAddress returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasEmailAddress() bool {
	if o != nil && o.EmailAddress.IsSet() {
		return true
	}

	return false
}

// SetEmailAddress gets a reference to the given NullableString and assigns it to the EmailAddress field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetEmailAddress(v string) {
	o.EmailAddress.Set(&v)
}
// SetEmailAddressNil sets the value for EmailAddress to be an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetEmailAddressNil() {
	o.EmailAddress.Set(nil)
}

// UnsetEmailAddress ensures that no value is present for EmailAddress, not even an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) UnsetEmailAddress() {
	o.EmailAddress.Unset()
}

// GetEmailAddressObserverList returns the EmailAddressObserverList field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetEmailAddressObserverList() []IntraService5CommonModelsMailAddress3450 {
	if o == nil {
		var ret []IntraService5CommonModelsMailAddress3450
		return ret
	}
	return o.EmailAddressObserverList
}

// GetEmailAddressObserverListOk returns a tuple with the EmailAddressObserverList field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetEmailAddressObserverListOk() ([]IntraService5CommonModelsMailAddress3450, bool) {
	if o == nil || IsNil(o.EmailAddressObserverList) {
		return nil, false
	}
	return o.EmailAddressObserverList, true
}

// HasEmailAddressObserverList returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasEmailAddressObserverList() bool {
	if o != nil && IsNil(o.EmailAddressObserverList) {
		return true
	}

	return false
}

// SetEmailAddressObserverList gets a reference to the given []IntraService5CommonModelsMailAddress3450 and assigns it to the EmailAddressObserverList field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetEmailAddressObserverList(v []IntraService5CommonModelsMailAddress3450) {
	o.EmailAddressObserverList = v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber.Get()) {
		var ret string
		return ret
	}
	return *o.PhoneNumber.Get()
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneNumber.Get(), o.PhoneNumber.IsSet()
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber.IsSet() {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given NullableString and assigns it to the PhoneNumber field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetPhoneNumber(v string) {
	o.PhoneNumber.Set(&v)
}
// SetPhoneNumberNil sets the value for PhoneNumber to be an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetPhoneNumberNil() {
	o.PhoneNumber.Set(nil)
}

// UnsetPhoneNumber ensures that no value is present for PhoneNumber, not even an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) UnsetPhoneNumber() {
	o.PhoneNumber.Unset()
}

// GetTelegramId returns the TelegramId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetTelegramId() int64 {
	if o == nil || IsNil(o.TelegramId.Get()) {
		var ret int64
		return ret
	}
	return *o.TelegramId.Get()
}

// GetTelegramIdOk returns a tuple with the TelegramId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetTelegramIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.TelegramId.Get(), o.TelegramId.IsSet()
}

// HasTelegramId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasTelegramId() bool {
	if o != nil && o.TelegramId.IsSet() {
		return true
	}

	return false
}

// SetTelegramId gets a reference to the given NullableInt64 and assigns it to the TelegramId field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetTelegramId(v int64) {
	o.TelegramId.Set(&v)
}
// SetTelegramIdNil sets the value for TelegramId to be an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetTelegramIdNil() {
	o.TelegramId.Set(nil)
}

// UnsetTelegramId ensures that no value is present for TelegramId, not even an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) UnsetTelegramId() {
	o.TelegramId.Unset()
}

// GetTelegramUserName returns the TelegramUserName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetTelegramUserName() string {
	if o == nil || IsNil(o.TelegramUserName.Get()) {
		var ret string
		return ret
	}
	return *o.TelegramUserName.Get()
}

// GetTelegramUserNameOk returns a tuple with the TelegramUserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetTelegramUserNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TelegramUserName.Get(), o.TelegramUserName.IsSet()
}

// HasTelegramUserName returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasTelegramUserName() bool {
	if o != nil && o.TelegramUserName.IsSet() {
		return true
	}

	return false
}

// SetTelegramUserName gets a reference to the given NullableString and assigns it to the TelegramUserName field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetTelegramUserName(v string) {
	o.TelegramUserName.Set(&v)
}
// SetTelegramUserNameNil sets the value for TelegramUserName to be an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetTelegramUserNameNil() {
	o.TelegramUserName.Set(nil)
}

// UnsetTelegramUserName ensures that no value is present for TelegramUserName, not even an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) UnsetTelegramUserName() {
	o.TelegramUserName.Unset()
}

// GetWebChatId returns the WebChatId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetWebChatId() string {
	if o == nil || IsNil(o.WebChatId.Get()) {
		var ret string
		return ret
	}
	return *o.WebChatId.Get()
}

// GetWebChatIdOk returns a tuple with the WebChatId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetWebChatIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebChatId.Get(), o.WebChatId.IsSet()
}

// HasWebChatId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasWebChatId() bool {
	if o != nil && o.WebChatId.IsSet() {
		return true
	}

	return false
}

// SetWebChatId gets a reference to the given NullableString and assigns it to the WebChatId field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetWebChatId(v string) {
	o.WebChatId.Set(&v)
}
// SetWebChatIdNil sets the value for WebChatId to be an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetWebChatIdNil() {
	o.WebChatId.Set(nil)
}

// UnsetWebChatId ensures that no value is present for WebChatId, not even an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) UnsetWebChatId() {
	o.WebChatId.Unset()
}

// GetUserFirstName returns the UserFirstName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetUserFirstName() string {
	if o == nil || IsNil(o.UserFirstName.Get()) {
		var ret string
		return ret
	}
	return *o.UserFirstName.Get()
}

// GetUserFirstNameOk returns a tuple with the UserFirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetUserFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserFirstName.Get(), o.UserFirstName.IsSet()
}

// HasUserFirstName returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasUserFirstName() bool {
	if o != nil && o.UserFirstName.IsSet() {
		return true
	}

	return false
}

// SetUserFirstName gets a reference to the given NullableString and assigns it to the UserFirstName field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetUserFirstName(v string) {
	o.UserFirstName.Set(&v)
}
// SetUserFirstNameNil sets the value for UserFirstName to be an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetUserFirstNameNil() {
	o.UserFirstName.Set(nil)
}

// UnsetUserFirstName ensures that no value is present for UserFirstName, not even an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) UnsetUserFirstName() {
	o.UserFirstName.Unset()
}

// GetUserLastName returns the UserLastName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetUserLastName() string {
	if o == nil || IsNil(o.UserLastName.Get()) {
		var ret string
		return ret
	}
	return *o.UserLastName.Get()
}

// GetUserLastNameOk returns a tuple with the UserLastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetUserLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserLastName.Get(), o.UserLastName.IsSet()
}

// HasUserLastName returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasUserLastName() bool {
	if o != nil && o.UserLastName.IsSet() {
		return true
	}

	return false
}

// SetUserLastName gets a reference to the given NullableString and assigns it to the UserLastName field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetUserLastName(v string) {
	o.UserLastName.Set(&v)
}
// SetUserLastNameNil sets the value for UserLastName to be an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetUserLastNameNil() {
	o.UserLastName.Set(nil)
}

// UnsetUserLastName ensures that no value is present for UserLastName, not even an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) UnsetUserLastName() {
	o.UserLastName.Unset()
}

// GetUserMiddleName returns the UserMiddleName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetUserMiddleName() string {
	if o == nil || IsNil(o.UserMiddleName.Get()) {
		var ret string
		return ret
	}
	return *o.UserMiddleName.Get()
}

// GetUserMiddleNameOk returns a tuple with the UserMiddleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetUserMiddleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserMiddleName.Get(), o.UserMiddleName.IsSet()
}

// HasUserMiddleName returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasUserMiddleName() bool {
	if o != nil && o.UserMiddleName.IsSet() {
		return true
	}

	return false
}

// SetUserMiddleName gets a reference to the given NullableString and assigns it to the UserMiddleName field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetUserMiddleName(v string) {
	o.UserMiddleName.Set(&v)
}
// SetUserMiddleNameNil sets the value for UserMiddleName to be an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetUserMiddleNameNil() {
	o.UserMiddleName.Set(nil)
}

// UnsetUserMiddleName ensures that no value is present for UserMiddleName, not even an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) UnsetUserMiddleName() {
	o.UserMiddleName.Unset()
}

// GetIsSelfRegistrationConsider returns the IsSelfRegistrationConsider field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetIsSelfRegistrationConsider() bool {
	if o == nil || IsNil(o.IsSelfRegistrationConsider) {
		var ret bool
		return ret
	}
	return *o.IsSelfRegistrationConsider
}

// GetIsSelfRegistrationConsiderOk returns a tuple with the IsSelfRegistrationConsider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetIsSelfRegistrationConsiderOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSelfRegistrationConsider) {
		return nil, false
	}
	return o.IsSelfRegistrationConsider, true
}

// HasIsSelfRegistrationConsider returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasIsSelfRegistrationConsider() bool {
	if o != nil && !IsNil(o.IsSelfRegistrationConsider) {
		return true
	}

	return false
}

// SetIsSelfRegistrationConsider gets a reference to the given bool and assigns it to the IsSelfRegistrationConsider field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetIsSelfRegistrationConsider(v bool) {
	o.IsSelfRegistrationConsider = &v
}

// GetFieldIdValues returns the FieldIdValues field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetFieldIdValues() []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 {
	if o == nil {
		var ret []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7
		return ret
	}
	return o.FieldIdValues
}

// GetFieldIdValuesOk returns a tuple with the FieldIdValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetFieldIdValuesOk() ([]IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7, bool) {
	if o == nil || IsNil(o.FieldIdValues) {
		return nil, false
	}
	return o.FieldIdValues, true
}

// HasFieldIdValues returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasFieldIdValues() bool {
	if o != nil && IsNil(o.FieldIdValues) {
		return true
	}

	return false
}

// SetFieldIdValues gets a reference to the given []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 and assigns it to the FieldIdValues field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetFieldIdValues(v []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) {
	o.FieldIdValues = v
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetPassword() string {
	if o == nil || IsNil(o.Password.Get()) {
		var ret string
		return ret
	}
	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// HasPassword returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasPassword() bool {
	if o != nil && o.Password.IsSet() {
		return true
	}

	return false
}

// SetPassword gets a reference to the given NullableString and assigns it to the Password field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetPassword(v string) {
	o.Password.Set(&v)
}
// SetPasswordNil sets the value for Password to be an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetPasswordNil() {
	o.Password.Set(nil)
}

// UnsetPassword ensures that no value is present for Password, not even an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) UnsetPassword() {
	o.Password.Unset()
}

// GetClientType returns the ClientType field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetClientType() IntraService5SharedEnumsClientType6CE9 {
	if o == nil || IsNil(o.ClientType) {
		var ret IntraService5SharedEnumsClientType6CE9
		return ret
	}
	return *o.ClientType
}

// GetClientTypeOk returns a tuple with the ClientType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetClientTypeOk() (*IntraService5SharedEnumsClientType6CE9, bool) {
	if o == nil || IsNil(o.ClientType) {
		return nil, false
	}
	return o.ClientType, true
}

// HasClientType returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasClientType() bool {
	if o != nil && !IsNil(o.ClientType) {
		return true
	}

	return false
}

// SetClientType gets a reference to the given IntraService5SharedEnumsClientType6CE9 and assigns it to the ClientType field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetClientType(v IntraService5SharedEnumsClientType6CE9) {
	o.ClientType = &v
}

// GetTaxpayerNumber returns the TaxpayerNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetTaxpayerNumber() string {
	if o == nil || IsNil(o.TaxpayerNumber.Get()) {
		var ret string
		return ret
	}
	return *o.TaxpayerNumber.Get()
}

// GetTaxpayerNumberOk returns a tuple with the TaxpayerNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetTaxpayerNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaxpayerNumber.Get(), o.TaxpayerNumber.IsSet()
}

// HasTaxpayerNumber returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasTaxpayerNumber() bool {
	if o != nil && o.TaxpayerNumber.IsSet() {
		return true
	}

	return false
}

// SetTaxpayerNumber gets a reference to the given NullableString and assigns it to the TaxpayerNumber field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetTaxpayerNumber(v string) {
	o.TaxpayerNumber.Set(&v)
}
// SetTaxpayerNumberNil sets the value for TaxpayerNumber to be an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetTaxpayerNumberNil() {
	o.TaxpayerNumber.Set(nil)
}

// UnsetTaxpayerNumber ensures that no value is present for TaxpayerNumber, not even an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) UnsetTaxpayerNumber() {
	o.TaxpayerNumber.Unset()
}

// GetWeb returns the Web field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetWeb() string {
	if o == nil || IsNil(o.Web.Get()) {
		var ret string
		return ret
	}
	return *o.Web.Get()
}

// GetWebOk returns a tuple with the Web field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetWebOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Web.Get(), o.Web.IsSet()
}

// HasWeb returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasWeb() bool {
	if o != nil && o.Web.IsSet() {
		return true
	}

	return false
}

// SetWeb gets a reference to the given NullableString and assigns it to the Web field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetWeb(v string) {
	o.Web.Set(&v)
}
// SetWebNil sets the value for Web to be an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetWebNil() {
	o.Web.Set(nil)
}

// UnsetWeb ensures that no value is present for Web, not even an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) UnsetWeb() {
	o.Web.Unset()
}

// GetClientName returns the ClientName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetClientName() string {
	if o == nil || IsNil(o.ClientName.Get()) {
		var ret string
		return ret
	}
	return *o.ClientName.Get()
}

// GetClientNameOk returns a tuple with the ClientName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetClientNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClientName.Get(), o.ClientName.IsSet()
}

// HasClientName returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasClientName() bool {
	if o != nil && o.ClientName.IsSet() {
		return true
	}

	return false
}

// SetClientName gets a reference to the given NullableString and assigns it to the ClientName field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetClientName(v string) {
	o.ClientName.Set(&v)
}
// SetClientNameNil sets the value for ClientName to be an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetClientNameNil() {
	o.ClientName.Set(nil)
}

// UnsetClientName ensures that no value is present for ClientName, not even an explicit nil
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) UnsetClientName() {
	o.ClientName.Unset()
}

// GetFieldValues returns the FieldValues field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetFieldValues() []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9 {
	if o == nil {
		var ret []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9
		return ret
	}
	return o.FieldValues
}

// GetFieldValuesOk returns a tuple with the FieldValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) GetFieldValuesOk() ([]IntraService5SettingsApiModelsAdditionalFieldValueModel86F9, bool) {
	if o == nil || IsNil(o.FieldValues) {
		return nil, false
	}
	return o.FieldValues, true
}

// HasFieldValues returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) HasFieldValues() bool {
	if o != nil && IsNil(o.FieldValues) {
		return true
	}

	return false
}

// SetFieldValues gets a reference to the given []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9 and assigns it to the FieldValues field.
func (o *IntraService5SettingsApiModelsInitClientUserInputModelE478) SetFieldValues(v []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9) {
	o.FieldValues = v
}

func (o IntraService5SettingsApiModelsInitClientUserInputModelE478) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntraService5SettingsApiModelsInitClientUserInputModelE478) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InitClientUserChannel) {
		toSerialize["initClientUserChannel"] = o.InitClientUserChannel
	}
	if o.EmailAddress.IsSet() {
		toSerialize["emailAddress"] = o.EmailAddress.Get()
	}
	if o.EmailAddressObserverList != nil {
		toSerialize["emailAddressObserverList"] = o.EmailAddressObserverList
	}
	if o.PhoneNumber.IsSet() {
		toSerialize["phoneNumber"] = o.PhoneNumber.Get()
	}
	if o.TelegramId.IsSet() {
		toSerialize["telegramId"] = o.TelegramId.Get()
	}
	if o.TelegramUserName.IsSet() {
		toSerialize["telegramUserName"] = o.TelegramUserName.Get()
	}
	if o.WebChatId.IsSet() {
		toSerialize["webChatId"] = o.WebChatId.Get()
	}
	if o.UserFirstName.IsSet() {
		toSerialize["userFirstName"] = o.UserFirstName.Get()
	}
	if o.UserLastName.IsSet() {
		toSerialize["userLastName"] = o.UserLastName.Get()
	}
	if o.UserMiddleName.IsSet() {
		toSerialize["userMiddleName"] = o.UserMiddleName.Get()
	}
	if !IsNil(o.IsSelfRegistrationConsider) {
		toSerialize["isSelfRegistrationConsider"] = o.IsSelfRegistrationConsider
	}
	if o.FieldIdValues != nil {
		toSerialize["fieldIdValues"] = o.FieldIdValues
	}
	if o.Password.IsSet() {
		toSerialize["password"] = o.Password.Get()
	}
	if !IsNil(o.ClientType) {
		toSerialize["clientType"] = o.ClientType
	}
	if o.TaxpayerNumber.IsSet() {
		toSerialize["taxpayerNumber"] = o.TaxpayerNumber.Get()
	}
	if o.Web.IsSet() {
		toSerialize["web"] = o.Web.Get()
	}
	if o.ClientName.IsSet() {
		toSerialize["clientName"] = o.ClientName.Get()
	}
	if o.FieldValues != nil {
		toSerialize["fieldValues"] = o.FieldValues
	}
	return toSerialize, nil
}

type NullableIntraService5SettingsApiModelsInitClientUserInputModelE478 struct {
	value *IntraService5SettingsApiModelsInitClientUserInputModelE478
	isSet bool
}

func (v NullableIntraService5SettingsApiModelsInitClientUserInputModelE478) Get() *IntraService5SettingsApiModelsInitClientUserInputModelE478 {
	return v.value
}

func (v *NullableIntraService5SettingsApiModelsInitClientUserInputModelE478) Set(val *IntraService5SettingsApiModelsInitClientUserInputModelE478) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5SettingsApiModelsInitClientUserInputModelE478) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5SettingsApiModelsInitClientUserInputModelE478) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5SettingsApiModelsInitClientUserInputModelE478(val *IntraService5SettingsApiModelsInitClientUserInputModelE478) *NullableIntraService5SettingsApiModelsInitClientUserInputModelE478 {
	return &NullableIntraService5SettingsApiModelsInitClientUserInputModelE478{value: val, isSet: true}
}

func (v NullableIntraService5SettingsApiModelsInitClientUserInputModelE478) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5SettingsApiModelsInitClientUserInputModelE478) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


