/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IntraService5SettingsApiModelsPhoneNumbersListDtoCB78 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntraService5SettingsApiModelsPhoneNumbersListDtoCB78{}

// IntraService5SettingsApiModelsPhoneNumbersListDtoCB78 struct for IntraService5SettingsApiModelsPhoneNumbersListDtoCB78
type IntraService5SettingsApiModelsPhoneNumbersListDtoCB78 struct {
	PhoneNumber NullableString `json:"phoneNumber,omitempty"`
	Default *bool `json:"default,omitempty"`
	PhoneExt NullableString `json:"phoneExt,omitempty"`
	PhoneInternational NullableString `json:"phoneInternational,omitempty"`
}

// NewIntraService5SettingsApiModelsPhoneNumbersListDtoCB78 instantiates a new IntraService5SettingsApiModelsPhoneNumbersListDtoCB78 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntraService5SettingsApiModelsPhoneNumbersListDtoCB78() *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78 {
	this := IntraService5SettingsApiModelsPhoneNumbersListDtoCB78{}
	return &this
}

// NewIntraService5SettingsApiModelsPhoneNumbersListDtoCB78WithDefaults instantiates a new IntraService5SettingsApiModelsPhoneNumbersListDtoCB78 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntraService5SettingsApiModelsPhoneNumbersListDtoCB78WithDefaults() *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78 {
	this := IntraService5SettingsApiModelsPhoneNumbersListDtoCB78{}
	return &this
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber.Get()) {
		var ret string
		return ret
	}
	return *o.PhoneNumber.Get()
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneNumber.Get(), o.PhoneNumber.IsSet()
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber.IsSet() {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given NullableString and assigns it to the PhoneNumber field.
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) SetPhoneNumber(v string) {
	o.PhoneNumber.Set(&v)
}
// SetPhoneNumberNil sets the value for PhoneNumber to be an explicit nil
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) SetPhoneNumberNil() {
	o.PhoneNumber.Set(nil)
}

// UnsetPhoneNumber ensures that no value is present for PhoneNumber, not even an explicit nil
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) UnsetPhoneNumber() {
	o.PhoneNumber.Unset()
}

// GetDefault returns the Default field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) GetDefault() bool {
	if o == nil || IsNil(o.Default) {
		var ret bool
		return ret
	}
	return *o.Default
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) GetDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.Default) {
		return nil, false
	}
	return o.Default, true
}

// HasDefault returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) HasDefault() bool {
	if o != nil && !IsNil(o.Default) {
		return true
	}

	return false
}

// SetDefault gets a reference to the given bool and assigns it to the Default field.
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) SetDefault(v bool) {
	o.Default = &v
}

// GetPhoneExt returns the PhoneExt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) GetPhoneExt() string {
	if o == nil || IsNil(o.PhoneExt.Get()) {
		var ret string
		return ret
	}
	return *o.PhoneExt.Get()
}

// GetPhoneExtOk returns a tuple with the PhoneExt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) GetPhoneExtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneExt.Get(), o.PhoneExt.IsSet()
}

// HasPhoneExt returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) HasPhoneExt() bool {
	if o != nil && o.PhoneExt.IsSet() {
		return true
	}

	return false
}

// SetPhoneExt gets a reference to the given NullableString and assigns it to the PhoneExt field.
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) SetPhoneExt(v string) {
	o.PhoneExt.Set(&v)
}
// SetPhoneExtNil sets the value for PhoneExt to be an explicit nil
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) SetPhoneExtNil() {
	o.PhoneExt.Set(nil)
}

// UnsetPhoneExt ensures that no value is present for PhoneExt, not even an explicit nil
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) UnsetPhoneExt() {
	o.PhoneExt.Unset()
}

// GetPhoneInternational returns the PhoneInternational field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) GetPhoneInternational() string {
	if o == nil || IsNil(o.PhoneInternational.Get()) {
		var ret string
		return ret
	}
	return *o.PhoneInternational.Get()
}

// GetPhoneInternationalOk returns a tuple with the PhoneInternational field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) GetPhoneInternationalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneInternational.Get(), o.PhoneInternational.IsSet()
}

// HasPhoneInternational returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) HasPhoneInternational() bool {
	if o != nil && o.PhoneInternational.IsSet() {
		return true
	}

	return false
}

// SetPhoneInternational gets a reference to the given NullableString and assigns it to the PhoneInternational field.
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) SetPhoneInternational(v string) {
	o.PhoneInternational.Set(&v)
}
// SetPhoneInternationalNil sets the value for PhoneInternational to be an explicit nil
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) SetPhoneInternationalNil() {
	o.PhoneInternational.Set(nil)
}

// UnsetPhoneInternational ensures that no value is present for PhoneInternational, not even an explicit nil
func (o *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) UnsetPhoneInternational() {
	o.PhoneInternational.Unset()
}

func (o IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.PhoneNumber.IsSet() {
		toSerialize["phoneNumber"] = o.PhoneNumber.Get()
	}
	if !IsNil(o.Default) {
		toSerialize["default"] = o.Default
	}
	if o.PhoneExt.IsSet() {
		toSerialize["phoneExt"] = o.PhoneExt.Get()
	}
	if o.PhoneInternational.IsSet() {
		toSerialize["phoneInternational"] = o.PhoneInternational.Get()
	}
	return toSerialize, nil
}

type NullableIntraService5SettingsApiModelsPhoneNumbersListDtoCB78 struct {
	value *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78
	isSet bool
}

func (v NullableIntraService5SettingsApiModelsPhoneNumbersListDtoCB78) Get() *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78 {
	return v.value
}

func (v *NullableIntraService5SettingsApiModelsPhoneNumbersListDtoCB78) Set(val *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5SettingsApiModelsPhoneNumbersListDtoCB78) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5SettingsApiModelsPhoneNumbersListDtoCB78) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5SettingsApiModelsPhoneNumbersListDtoCB78(val *IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) *NullableIntraService5SettingsApiModelsPhoneNumbersListDtoCB78 {
	return &NullableIntraService5SettingsApiModelsPhoneNumbersListDtoCB78{value: val, isSet: true}
}

func (v NullableIntraService5SettingsApiModelsPhoneNumbersListDtoCB78) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5SettingsApiModelsPhoneNumbersListDtoCB78) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


