/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the IntraService5SettingsApiModelsSearchHintsModel3054 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntraService5SettingsApiModelsSearchHintsModel3054{}

// IntraService5SettingsApiModelsSearchHintsModel3054 struct for IntraService5SettingsApiModelsSearchHintsModel3054
type IntraService5SettingsApiModelsSearchHintsModel3054 struct {
	Id NullableInt64 `json:"id,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	Name NullableString `json:"name,omitempty"`
	Description NullableString `json:"description,omitempty"`
	NamePath NullableString `json:"namePath,omitempty"`
	FullName NullableString `json:"fullName,omitempty"`
	Level NullableInt64 `json:"level,omitempty"`
	Path NullableString `json:"path,omitempty"`
	IsArchived NullableBool `json:"isArchived,omitempty"`
}

// NewIntraService5SettingsApiModelsSearchHintsModel3054 instantiates a new IntraService5SettingsApiModelsSearchHintsModel3054 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntraService5SettingsApiModelsSearchHintsModel3054() *IntraService5SettingsApiModelsSearchHintsModel3054 {
	this := IntraService5SettingsApiModelsSearchHintsModel3054{}
	return &this
}

// NewIntraService5SettingsApiModelsSearchHintsModel3054WithDefaults instantiates a new IntraService5SettingsApiModelsSearchHintsModel3054 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntraService5SettingsApiModelsSearchHintsModel3054WithDefaults() *IntraService5SettingsApiModelsSearchHintsModel3054 {
	this := IntraService5SettingsApiModelsSearchHintsModel3054{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetId() int64 {
	if o == nil || IsNil(o.Id.Get()) {
		var ret int64
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableInt64 and assigns it to the Id field.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetId(v int64) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) UnsetId() {
	o.Id.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) UnsetDescription() {
	o.Description.Unset()
}

// GetNamePath returns the NamePath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetNamePath() string {
	if o == nil || IsNil(o.NamePath.Get()) {
		var ret string
		return ret
	}
	return *o.NamePath.Get()
}

// GetNamePathOk returns a tuple with the NamePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetNamePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NamePath.Get(), o.NamePath.IsSet()
}

// HasNamePath returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) HasNamePath() bool {
	if o != nil && o.NamePath.IsSet() {
		return true
	}

	return false
}

// SetNamePath gets a reference to the given NullableString and assigns it to the NamePath field.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetNamePath(v string) {
	o.NamePath.Set(&v)
}
// SetNamePathNil sets the value for NamePath to be an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetNamePathNil() {
	o.NamePath.Set(nil)
}

// UnsetNamePath ensures that no value is present for NamePath, not even an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) UnsetNamePath() {
	o.NamePath.Unset()
}

// GetFullName returns the FullName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetFullName() string {
	if o == nil || IsNil(o.FullName.Get()) {
		var ret string
		return ret
	}
	return *o.FullName.Get()
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetFullNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FullName.Get(), o.FullName.IsSet()
}

// HasFullName returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) HasFullName() bool {
	if o != nil && o.FullName.IsSet() {
		return true
	}

	return false
}

// SetFullName gets a reference to the given NullableString and assigns it to the FullName field.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetFullName(v string) {
	o.FullName.Set(&v)
}
// SetFullNameNil sets the value for FullName to be an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetFullNameNil() {
	o.FullName.Set(nil)
}

// UnsetFullName ensures that no value is present for FullName, not even an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) UnsetFullName() {
	o.FullName.Unset()
}

// GetLevel returns the Level field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetLevel() int64 {
	if o == nil || IsNil(o.Level.Get()) {
		var ret int64
		return ret
	}
	return *o.Level.Get()
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetLevelOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Level.Get(), o.Level.IsSet()
}

// HasLevel returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) HasLevel() bool {
	if o != nil && o.Level.IsSet() {
		return true
	}

	return false
}

// SetLevel gets a reference to the given NullableInt64 and assigns it to the Level field.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetLevel(v int64) {
	o.Level.Set(&v)
}
// SetLevelNil sets the value for Level to be an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetLevelNil() {
	o.Level.Set(nil)
}

// UnsetLevel ensures that no value is present for Level, not even an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) UnsetLevel() {
	o.Level.Unset()
}

// GetPath returns the Path field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetPath() string {
	if o == nil || IsNil(o.Path.Get()) {
		var ret string
		return ret
	}
	return *o.Path.Get()
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Path.Get(), o.Path.IsSet()
}

// HasPath returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) HasPath() bool {
	if o != nil && o.Path.IsSet() {
		return true
	}

	return false
}

// SetPath gets a reference to the given NullableString and assigns it to the Path field.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetPath(v string) {
	o.Path.Set(&v)
}
// SetPathNil sets the value for Path to be an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetPathNil() {
	o.Path.Set(nil)
}

// UnsetPath ensures that no value is present for Path, not even an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) UnsetPath() {
	o.Path.Unset()
}

// GetIsArchived returns the IsArchived field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetIsArchived() bool {
	if o == nil || IsNil(o.IsArchived.Get()) {
		var ret bool
		return ret
	}
	return *o.IsArchived.Get()
}

// GetIsArchivedOk returns a tuple with the IsArchived field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) GetIsArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsArchived.Get(), o.IsArchived.IsSet()
}

// HasIsArchived returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) HasIsArchived() bool {
	if o != nil && o.IsArchived.IsSet() {
		return true
	}

	return false
}

// SetIsArchived gets a reference to the given NullableBool and assigns it to the IsArchived field.
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetIsArchived(v bool) {
	o.IsArchived.Set(&v)
}
// SetIsArchivedNil sets the value for IsArchived to be an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) SetIsArchivedNil() {
	o.IsArchived.Set(nil)
}

// UnsetIsArchived ensures that no value is present for IsArchived, not even an explicit nil
func (o *IntraService5SettingsApiModelsSearchHintsModel3054) UnsetIsArchived() {
	o.IsArchived.Unset()
}

func (o IntraService5SettingsApiModelsSearchHintsModel3054) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntraService5SettingsApiModelsSearchHintsModel3054) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.NamePath.IsSet() {
		toSerialize["namePath"] = o.NamePath.Get()
	}
	if o.FullName.IsSet() {
		toSerialize["fullName"] = o.FullName.Get()
	}
	if o.Level.IsSet() {
		toSerialize["level"] = o.Level.Get()
	}
	if o.Path.IsSet() {
		toSerialize["path"] = o.Path.Get()
	}
	if o.IsArchived.IsSet() {
		toSerialize["isArchived"] = o.IsArchived.Get()
	}
	return toSerialize, nil
}

type NullableIntraService5SettingsApiModelsSearchHintsModel3054 struct {
	value *IntraService5SettingsApiModelsSearchHintsModel3054
	isSet bool
}

func (v NullableIntraService5SettingsApiModelsSearchHintsModel3054) Get() *IntraService5SettingsApiModelsSearchHintsModel3054 {
	return v.value
}

func (v *NullableIntraService5SettingsApiModelsSearchHintsModel3054) Set(val *IntraService5SettingsApiModelsSearchHintsModel3054) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5SettingsApiModelsSearchHintsModel3054) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5SettingsApiModelsSearchHintsModel3054) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5SettingsApiModelsSearchHintsModel3054(val *IntraService5SettingsApiModelsSearchHintsModel3054) *NullableIntraService5SettingsApiModelsSearchHintsModel3054 {
	return &NullableIntraService5SettingsApiModelsSearchHintsModel3054{value: val, isSet: true}
}

func (v NullableIntraService5SettingsApiModelsSearchHintsModel3054) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5SettingsApiModelsSearchHintsModel3054) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


