/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IntraService5SettingsApiModelsClientsMergeClientUsersModelF151 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntraService5SettingsApiModelsClientsMergeClientUsersModelF151{}

// IntraService5SettingsApiModelsClientsMergeClientUsersModelF151 struct for IntraService5SettingsApiModelsClientsMergeClientUsersModelF151
type IntraService5SettingsApiModelsClientsMergeClientUsersModelF151 struct {
	ClientId *int64 `json:"clientId,omitempty"`
	MainUserId *int64 `json:"mainUserId,omitempty"`
	DeletedUserId *int64 `json:"deletedUserId,omitempty"`
	TaskCountLimit *int32 `json:"taskCountLimit,omitempty"`
}

// NewIntraService5SettingsApiModelsClientsMergeClientUsersModelF151 instantiates a new IntraService5SettingsApiModelsClientsMergeClientUsersModelF151 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntraService5SettingsApiModelsClientsMergeClientUsersModelF151() *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151 {
	this := IntraService5SettingsApiModelsClientsMergeClientUsersModelF151{}
	return &this
}

// NewIntraService5SettingsApiModelsClientsMergeClientUsersModelF151WithDefaults instantiates a new IntraService5SettingsApiModelsClientsMergeClientUsersModelF151 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntraService5SettingsApiModelsClientsMergeClientUsersModelF151WithDefaults() *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151 {
	this := IntraService5SettingsApiModelsClientsMergeClientUsersModelF151{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) GetClientId() int64 {
	if o == nil || IsNil(o.ClientId) {
		var ret int64
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) GetClientIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given int64 and assigns it to the ClientId field.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) SetClientId(v int64) {
	o.ClientId = &v
}

// GetMainUserId returns the MainUserId field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) GetMainUserId() int64 {
	if o == nil || IsNil(o.MainUserId) {
		var ret int64
		return ret
	}
	return *o.MainUserId
}

// GetMainUserIdOk returns a tuple with the MainUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) GetMainUserIdOk() (*int64, bool) {
	if o == nil || IsNil(o.MainUserId) {
		return nil, false
	}
	return o.MainUserId, true
}

// HasMainUserId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) HasMainUserId() bool {
	if o != nil && !IsNil(o.MainUserId) {
		return true
	}

	return false
}

// SetMainUserId gets a reference to the given int64 and assigns it to the MainUserId field.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) SetMainUserId(v int64) {
	o.MainUserId = &v
}

// GetDeletedUserId returns the DeletedUserId field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) GetDeletedUserId() int64 {
	if o == nil || IsNil(o.DeletedUserId) {
		var ret int64
		return ret
	}
	return *o.DeletedUserId
}

// GetDeletedUserIdOk returns a tuple with the DeletedUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) GetDeletedUserIdOk() (*int64, bool) {
	if o == nil || IsNil(o.DeletedUserId) {
		return nil, false
	}
	return o.DeletedUserId, true
}

// HasDeletedUserId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) HasDeletedUserId() bool {
	if o != nil && !IsNil(o.DeletedUserId) {
		return true
	}

	return false
}

// SetDeletedUserId gets a reference to the given int64 and assigns it to the DeletedUserId field.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) SetDeletedUserId(v int64) {
	o.DeletedUserId = &v
}

// GetTaskCountLimit returns the TaskCountLimit field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) GetTaskCountLimit() int32 {
	if o == nil || IsNil(o.TaskCountLimit) {
		var ret int32
		return ret
	}
	return *o.TaskCountLimit
}

// GetTaskCountLimitOk returns a tuple with the TaskCountLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) GetTaskCountLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.TaskCountLimit) {
		return nil, false
	}
	return o.TaskCountLimit, true
}

// HasTaskCountLimit returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) HasTaskCountLimit() bool {
	if o != nil && !IsNil(o.TaskCountLimit) {
		return true
	}

	return false
}

// SetTaskCountLimit gets a reference to the given int32 and assigns it to the TaskCountLimit field.
func (o *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) SetTaskCountLimit(v int32) {
	o.TaskCountLimit = &v
}

func (o IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClientId) {
		toSerialize["clientId"] = o.ClientId
	}
	if !IsNil(o.MainUserId) {
		toSerialize["mainUserId"] = o.MainUserId
	}
	if !IsNil(o.DeletedUserId) {
		toSerialize["deletedUserId"] = o.DeletedUserId
	}
	if !IsNil(o.TaskCountLimit) {
		toSerialize["taskCountLimit"] = o.TaskCountLimit
	}
	return toSerialize, nil
}

type NullableIntraService5SettingsApiModelsClientsMergeClientUsersModelF151 struct {
	value *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151
	isSet bool
}

func (v NullableIntraService5SettingsApiModelsClientsMergeClientUsersModelF151) Get() *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151 {
	return v.value
}

func (v *NullableIntraService5SettingsApiModelsClientsMergeClientUsersModelF151) Set(val *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5SettingsApiModelsClientsMergeClientUsersModelF151) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5SettingsApiModelsClientsMergeClientUsersModelF151) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5SettingsApiModelsClientsMergeClientUsersModelF151(val *IntraService5SettingsApiModelsClientsMergeClientUsersModelF151) *NullableIntraService5SettingsApiModelsClientsMergeClientUsersModelF151 {
	return &NullableIntraService5SettingsApiModelsClientsMergeClientUsersModelF151{value: val, isSet: true}
}

func (v NullableIntraService5SettingsApiModelsClientsMergeClientUsersModelF151) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5SettingsApiModelsClientsMergeClientUsersModelF151) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


