/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7{}

// IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 struct for IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7
type IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 struct {
	Id *int64 `json:"id,omitempty"`
	Value NullableString `json:"value,omitempty"`
	Type *IntraService5SharedEnumsFieldType3A22 `json:"type,omitempty"`
}

// NewIntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 instantiates a new IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7() *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 {
	this := IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7{}
	return &this
}

// NewIntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7WithDefaults instantiates a new IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7WithDefaults() *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 {
	this := IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) SetId(v int64) {
	o.Id = &v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) GetValue() string {
	if o == nil || IsNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) SetValue(v string) {
	o.Value.Set(&v)
}
// SetValueNil sets the value for Value to be an explicit nil
func (o *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) UnsetValue() {
	o.Value.Unset()
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) GetType() IntraService5SharedEnumsFieldType3A22 {
	if o == nil || IsNil(o.Type) {
		var ret IntraService5SharedEnumsFieldType3A22
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) GetTypeOk() (*IntraService5SharedEnumsFieldType3A22, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given IntraService5SharedEnumsFieldType3A22 and assigns it to the Type field.
func (o *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) SetType(v IntraService5SharedEnumsFieldType3A22) {
	o.Type = &v
}

func (o IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableIntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 struct {
	value *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7
	isSet bool
}

func (v NullableIntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) Get() *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 {
	return v.value
}

func (v *NullableIntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) Set(val *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7(val *IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) *NullableIntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 {
	return &NullableIntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7{value: val, isSet: true}
}

func (v NullableIntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


