/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IntraService5SettingsApiModelsEntitiesDeletionModel18E3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntraService5SettingsApiModelsEntitiesDeletionModel18E3{}

// IntraService5SettingsApiModelsEntitiesDeletionModel18E3 struct for IntraService5SettingsApiModelsEntitiesDeletionModel18E3
type IntraService5SettingsApiModelsEntitiesDeletionModel18E3 struct {
	Ids []int64 `json:"ids,omitempty"`
	IsTotalDeletion *bool `json:"isTotalDeletion,omitempty"`
	CorrelationId *string `json:"correlationId,omitempty"`
}

// NewIntraService5SettingsApiModelsEntitiesDeletionModel18E3 instantiates a new IntraService5SettingsApiModelsEntitiesDeletionModel18E3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntraService5SettingsApiModelsEntitiesDeletionModel18E3() *IntraService5SettingsApiModelsEntitiesDeletionModel18E3 {
	this := IntraService5SettingsApiModelsEntitiesDeletionModel18E3{}
	return &this
}

// NewIntraService5SettingsApiModelsEntitiesDeletionModel18E3WithDefaults instantiates a new IntraService5SettingsApiModelsEntitiesDeletionModel18E3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntraService5SettingsApiModelsEntitiesDeletionModel18E3WithDefaults() *IntraService5SettingsApiModelsEntitiesDeletionModel18E3 {
	this := IntraService5SettingsApiModelsEntitiesDeletionModel18E3{}
	return &this
}

// GetIds returns the Ids field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsEntitiesDeletionModel18E3) GetIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}
	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsEntitiesDeletionModel18E3) GetIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.Ids) {
		return nil, false
	}
	return o.Ids, true
}

// HasIds returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsEntitiesDeletionModel18E3) HasIds() bool {
	if o != nil && IsNil(o.Ids) {
		return true
	}

	return false
}

// SetIds gets a reference to the given []int64 and assigns it to the Ids field.
func (o *IntraService5SettingsApiModelsEntitiesDeletionModel18E3) SetIds(v []int64) {
	o.Ids = v
}

// GetIsTotalDeletion returns the IsTotalDeletion field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsEntitiesDeletionModel18E3) GetIsTotalDeletion() bool {
	if o == nil || IsNil(o.IsTotalDeletion) {
		var ret bool
		return ret
	}
	return *o.IsTotalDeletion
}

// GetIsTotalDeletionOk returns a tuple with the IsTotalDeletion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsEntitiesDeletionModel18E3) GetIsTotalDeletionOk() (*bool, bool) {
	if o == nil || IsNil(o.IsTotalDeletion) {
		return nil, false
	}
	return o.IsTotalDeletion, true
}

// HasIsTotalDeletion returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsEntitiesDeletionModel18E3) HasIsTotalDeletion() bool {
	if o != nil && !IsNil(o.IsTotalDeletion) {
		return true
	}

	return false
}

// SetIsTotalDeletion gets a reference to the given bool and assigns it to the IsTotalDeletion field.
func (o *IntraService5SettingsApiModelsEntitiesDeletionModel18E3) SetIsTotalDeletion(v bool) {
	o.IsTotalDeletion = &v
}

// GetCorrelationId returns the CorrelationId field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsEntitiesDeletionModel18E3) GetCorrelationId() string {
	if o == nil || IsNil(o.CorrelationId) {
		var ret string
		return ret
	}
	return *o.CorrelationId
}

// GetCorrelationIdOk returns a tuple with the CorrelationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsEntitiesDeletionModel18E3) GetCorrelationIdOk() (*string, bool) {
	if o == nil || IsNil(o.CorrelationId) {
		return nil, false
	}
	return o.CorrelationId, true
}

// HasCorrelationId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsEntitiesDeletionModel18E3) HasCorrelationId() bool {
	if o != nil && !IsNil(o.CorrelationId) {
		return true
	}

	return false
}

// SetCorrelationId gets a reference to the given string and assigns it to the CorrelationId field.
func (o *IntraService5SettingsApiModelsEntitiesDeletionModel18E3) SetCorrelationId(v string) {
	o.CorrelationId = &v
}

func (o IntraService5SettingsApiModelsEntitiesDeletionModel18E3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntraService5SettingsApiModelsEntitiesDeletionModel18E3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Ids != nil {
		toSerialize["ids"] = o.Ids
	}
	if !IsNil(o.IsTotalDeletion) {
		toSerialize["isTotalDeletion"] = o.IsTotalDeletion
	}
	if !IsNil(o.CorrelationId) {
		toSerialize["correlationId"] = o.CorrelationId
	}
	return toSerialize, nil
}

type NullableIntraService5SettingsApiModelsEntitiesDeletionModel18E3 struct {
	value *IntraService5SettingsApiModelsEntitiesDeletionModel18E3
	isSet bool
}

func (v NullableIntraService5SettingsApiModelsEntitiesDeletionModel18E3) Get() *IntraService5SettingsApiModelsEntitiesDeletionModel18E3 {
	return v.value
}

func (v *NullableIntraService5SettingsApiModelsEntitiesDeletionModel18E3) Set(val *IntraService5SettingsApiModelsEntitiesDeletionModel18E3) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5SettingsApiModelsEntitiesDeletionModel18E3) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5SettingsApiModelsEntitiesDeletionModel18E3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5SettingsApiModelsEntitiesDeletionModel18E3(val *IntraService5SettingsApiModelsEntitiesDeletionModel18E3) *NullableIntraService5SettingsApiModelsEntitiesDeletionModel18E3 {
	return &NullableIntraService5SettingsApiModelsEntitiesDeletionModel18E3{value: val, isSet: true}
}

func (v NullableIntraService5SettingsApiModelsEntitiesDeletionModel18E3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5SettingsApiModelsEntitiesDeletionModel18E3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


