/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the IntraService5SettingsApiModelsClientLegalEntityModel62ED type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntraService5SettingsApiModelsClientLegalEntityModel62ED{}

// IntraService5SettingsApiModelsClientLegalEntityModel62ED struct for IntraService5SettingsApiModelsClientLegalEntityModel62ED
type IntraService5SettingsApiModelsClientLegalEntityModel62ED struct {
	Id *int64 `json:"id,omitempty"`
	Description NullableString `json:"description,omitempty"`
	IsArchived *bool `json:"isArchived,omitempty"`
	TimeZoneCode NullableString `json:"timeZoneCode,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	UpdatedBy NullableString `json:"updatedBy,omitempty"`
	Language NullableString `json:"language,omitempty"`
	Address NullableString `json:"address,omitempty"`
	Web NullableString `json:"web,omitempty"`
	Domains []string `json:"domains,omitempty"`
	UserGroupTags []IntraService5SettingsApiModelsBaseNamedModel10D7 `json:"userGroupTags,omitempty"`
	FieldsValues []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9 `json:"fieldsValues,omitempty"`
	FieldIdValues []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 `json:"fieldIdValues,omitempty"`
	ManagerId NullableInt64 `json:"managerId,omitempty"`
	Name NullableString `json:"name,omitempty"`
	TaxpayerNumber NullableString `json:"taxpayerNumber,omitempty"`
	Email NullableString `json:"email,omitempty"`
	PhoneNumbersList []IntraService5SettingsApiModelsPhoneNumbersListDtoCB78 `json:"phoneNumbersList,omitempty"`
	ContactPersonId NullableInt64 `json:"contactPersonId,omitempty"`
	AdditionalData map[string]interface{} `json:"additionalData,omitempty"`
}

// NewIntraService5SettingsApiModelsClientLegalEntityModel62ED instantiates a new IntraService5SettingsApiModelsClientLegalEntityModel62ED object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntraService5SettingsApiModelsClientLegalEntityModel62ED() *IntraService5SettingsApiModelsClientLegalEntityModel62ED {
	this := IntraService5SettingsApiModelsClientLegalEntityModel62ED{}
	return &this
}

// NewIntraService5SettingsApiModelsClientLegalEntityModel62EDWithDefaults instantiates a new IntraService5SettingsApiModelsClientLegalEntityModel62ED object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntraService5SettingsApiModelsClientLegalEntityModel62EDWithDefaults() *IntraService5SettingsApiModelsClientLegalEntityModel62ED {
	this := IntraService5SettingsApiModelsClientLegalEntityModel62ED{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetId(v int64) {
	o.Id = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) UnsetDescription() {
	o.Description.Unset()
}

// GetIsArchived returns the IsArchived field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetIsArchived() bool {
	if o == nil || IsNil(o.IsArchived) {
		var ret bool
		return ret
	}
	return *o.IsArchived
}

// GetIsArchivedOk returns a tuple with the IsArchived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetIsArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsArchived) {
		return nil, false
	}
	return o.IsArchived, true
}

// HasIsArchived returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasIsArchived() bool {
	if o != nil && !IsNil(o.IsArchived) {
		return true
	}

	return false
}

// SetIsArchived gets a reference to the given bool and assigns it to the IsArchived field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetIsArchived(v bool) {
	o.IsArchived = &v
}

// GetTimeZoneCode returns the TimeZoneCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetTimeZoneCode() string {
	if o == nil || IsNil(o.TimeZoneCode.Get()) {
		var ret string
		return ret
	}
	return *o.TimeZoneCode.Get()
}

// GetTimeZoneCodeOk returns a tuple with the TimeZoneCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetTimeZoneCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimeZoneCode.Get(), o.TimeZoneCode.IsSet()
}

// HasTimeZoneCode returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasTimeZoneCode() bool {
	if o != nil && o.TimeZoneCode.IsSet() {
		return true
	}

	return false
}

// SetTimeZoneCode gets a reference to the given NullableString and assigns it to the TimeZoneCode field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetTimeZoneCode(v string) {
	o.TimeZoneCode.Set(&v)
}
// SetTimeZoneCodeNil sets the value for TimeZoneCode to be an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetTimeZoneCodeNil() {
	o.TimeZoneCode.Set(nil)
}

// UnsetTimeZoneCode ensures that no value is present for TimeZoneCode, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) UnsetTimeZoneCode() {
	o.TimeZoneCode.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetUpdatedBy() string {
	if o == nil || IsNil(o.UpdatedBy.Get()) {
		var ret string
		return ret
	}
	return *o.UpdatedBy.Get()
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetUpdatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedBy.Get(), o.UpdatedBy.IsSet()
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasUpdatedBy() bool {
	if o != nil && o.UpdatedBy.IsSet() {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given NullableString and assigns it to the UpdatedBy field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetUpdatedBy(v string) {
	o.UpdatedBy.Set(&v)
}
// SetUpdatedByNil sets the value for UpdatedBy to be an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetUpdatedByNil() {
	o.UpdatedBy.Set(nil)
}

// UnsetUpdatedBy ensures that no value is present for UpdatedBy, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) UnsetUpdatedBy() {
	o.UpdatedBy.Unset()
}

// GetLanguage returns the Language field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetLanguage() string {
	if o == nil || IsNil(o.Language.Get()) {
		var ret string
		return ret
	}
	return *o.Language.Get()
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Language.Get(), o.Language.IsSet()
}

// HasLanguage returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasLanguage() bool {
	if o != nil && o.Language.IsSet() {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given NullableString and assigns it to the Language field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetLanguage(v string) {
	o.Language.Set(&v)
}
// SetLanguageNil sets the value for Language to be an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetLanguageNil() {
	o.Language.Set(nil)
}

// UnsetLanguage ensures that no value is present for Language, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) UnsetLanguage() {
	o.Language.Unset()
}

// GetAddress returns the Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetAddress() string {
	if o == nil || IsNil(o.Address.Get()) {
		var ret string
		return ret
	}
	return *o.Address.Get()
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address.Get(), o.Address.IsSet()
}

// HasAddress returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasAddress() bool {
	if o != nil && o.Address.IsSet() {
		return true
	}

	return false
}

// SetAddress gets a reference to the given NullableString and assigns it to the Address field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetAddress(v string) {
	o.Address.Set(&v)
}
// SetAddressNil sets the value for Address to be an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetAddressNil() {
	o.Address.Set(nil)
}

// UnsetAddress ensures that no value is present for Address, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) UnsetAddress() {
	o.Address.Unset()
}

// GetWeb returns the Web field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetWeb() string {
	if o == nil || IsNil(o.Web.Get()) {
		var ret string
		return ret
	}
	return *o.Web.Get()
}

// GetWebOk returns a tuple with the Web field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetWebOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Web.Get(), o.Web.IsSet()
}

// HasWeb returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasWeb() bool {
	if o != nil && o.Web.IsSet() {
		return true
	}

	return false
}

// SetWeb gets a reference to the given NullableString and assigns it to the Web field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetWeb(v string) {
	o.Web.Set(&v)
}
// SetWebNil sets the value for Web to be an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetWebNil() {
	o.Web.Set(nil)
}

// UnsetWeb ensures that no value is present for Web, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) UnsetWeb() {
	o.Web.Unset()
}

// GetDomains returns the Domains field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetDomains() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetDomainsOk() ([]string, bool) {
	if o == nil || IsNil(o.Domains) {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasDomains() bool {
	if o != nil && IsNil(o.Domains) {
		return true
	}

	return false
}

// SetDomains gets a reference to the given []string and assigns it to the Domains field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetDomains(v []string) {
	o.Domains = v
}

// GetUserGroupTags returns the UserGroupTags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetUserGroupTags() []IntraService5SettingsApiModelsBaseNamedModel10D7 {
	if o == nil {
		var ret []IntraService5SettingsApiModelsBaseNamedModel10D7
		return ret
	}
	return o.UserGroupTags
}

// GetUserGroupTagsOk returns a tuple with the UserGroupTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetUserGroupTagsOk() ([]IntraService5SettingsApiModelsBaseNamedModel10D7, bool) {
	if o == nil || IsNil(o.UserGroupTags) {
		return nil, false
	}
	return o.UserGroupTags, true
}

// HasUserGroupTags returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasUserGroupTags() bool {
	if o != nil && IsNil(o.UserGroupTags) {
		return true
	}

	return false
}

// SetUserGroupTags gets a reference to the given []IntraService5SettingsApiModelsBaseNamedModel10D7 and assigns it to the UserGroupTags field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetUserGroupTags(v []IntraService5SettingsApiModelsBaseNamedModel10D7) {
	o.UserGroupTags = v
}

// GetFieldsValues returns the FieldsValues field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetFieldsValues() []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9 {
	if o == nil {
		var ret []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9
		return ret
	}
	return o.FieldsValues
}

// GetFieldsValuesOk returns a tuple with the FieldsValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetFieldsValuesOk() ([]IntraService5SettingsApiModelsAdditionalFieldValueModel86F9, bool) {
	if o == nil || IsNil(o.FieldsValues) {
		return nil, false
	}
	return o.FieldsValues, true
}

// HasFieldsValues returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasFieldsValues() bool {
	if o != nil && IsNil(o.FieldsValues) {
		return true
	}

	return false
}

// SetFieldsValues gets a reference to the given []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9 and assigns it to the FieldsValues field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetFieldsValues(v []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9) {
	o.FieldsValues = v
}

// GetFieldIdValues returns the FieldIdValues field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetFieldIdValues() []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 {
	if o == nil {
		var ret []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7
		return ret
	}
	return o.FieldIdValues
}

// GetFieldIdValuesOk returns a tuple with the FieldIdValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetFieldIdValuesOk() ([]IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7, bool) {
	if o == nil || IsNil(o.FieldIdValues) {
		return nil, false
	}
	return o.FieldIdValues, true
}

// HasFieldIdValues returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasFieldIdValues() bool {
	if o != nil && IsNil(o.FieldIdValues) {
		return true
	}

	return false
}

// SetFieldIdValues gets a reference to the given []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 and assigns it to the FieldIdValues field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetFieldIdValues(v []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) {
	o.FieldIdValues = v
}

// GetManagerId returns the ManagerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetManagerId() int64 {
	if o == nil || IsNil(o.ManagerId.Get()) {
		var ret int64
		return ret
	}
	return *o.ManagerId.Get()
}

// GetManagerIdOk returns a tuple with the ManagerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetManagerIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ManagerId.Get(), o.ManagerId.IsSet()
}

// HasManagerId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasManagerId() bool {
	if o != nil && o.ManagerId.IsSet() {
		return true
	}

	return false
}

// SetManagerId gets a reference to the given NullableInt64 and assigns it to the ManagerId field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetManagerId(v int64) {
	o.ManagerId.Set(&v)
}
// SetManagerIdNil sets the value for ManagerId to be an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetManagerIdNil() {
	o.ManagerId.Set(nil)
}

// UnsetManagerId ensures that no value is present for ManagerId, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) UnsetManagerId() {
	o.ManagerId.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) UnsetName() {
	o.Name.Unset()
}

// GetTaxpayerNumber returns the TaxpayerNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetTaxpayerNumber() string {
	if o == nil || IsNil(o.TaxpayerNumber.Get()) {
		var ret string
		return ret
	}
	return *o.TaxpayerNumber.Get()
}

// GetTaxpayerNumberOk returns a tuple with the TaxpayerNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetTaxpayerNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaxpayerNumber.Get(), o.TaxpayerNumber.IsSet()
}

// HasTaxpayerNumber returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasTaxpayerNumber() bool {
	if o != nil && o.TaxpayerNumber.IsSet() {
		return true
	}

	return false
}

// SetTaxpayerNumber gets a reference to the given NullableString and assigns it to the TaxpayerNumber field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetTaxpayerNumber(v string) {
	o.TaxpayerNumber.Set(&v)
}
// SetTaxpayerNumberNil sets the value for TaxpayerNumber to be an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetTaxpayerNumberNil() {
	o.TaxpayerNumber.Set(nil)
}

// UnsetTaxpayerNumber ensures that no value is present for TaxpayerNumber, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) UnsetTaxpayerNumber() {
	o.TaxpayerNumber.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetEmail(v string) {
	o.Email.Set(&v)
}
// SetEmailNil sets the value for Email to be an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) UnsetEmail() {
	o.Email.Unset()
}

// GetPhoneNumbersList returns the PhoneNumbersList field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetPhoneNumbersList() []IntraService5SettingsApiModelsPhoneNumbersListDtoCB78 {
	if o == nil {
		var ret []IntraService5SettingsApiModelsPhoneNumbersListDtoCB78
		return ret
	}
	return o.PhoneNumbersList
}

// GetPhoneNumbersListOk returns a tuple with the PhoneNumbersList field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetPhoneNumbersListOk() ([]IntraService5SettingsApiModelsPhoneNumbersListDtoCB78, bool) {
	if o == nil || IsNil(o.PhoneNumbersList) {
		return nil, false
	}
	return o.PhoneNumbersList, true
}

// HasPhoneNumbersList returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasPhoneNumbersList() bool {
	if o != nil && IsNil(o.PhoneNumbersList) {
		return true
	}

	return false
}

// SetPhoneNumbersList gets a reference to the given []IntraService5SettingsApiModelsPhoneNumbersListDtoCB78 and assigns it to the PhoneNumbersList field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetPhoneNumbersList(v []IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) {
	o.PhoneNumbersList = v
}

// GetContactPersonId returns the ContactPersonId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetContactPersonId() int64 {
	if o == nil || IsNil(o.ContactPersonId.Get()) {
		var ret int64
		return ret
	}
	return *o.ContactPersonId.Get()
}

// GetContactPersonIdOk returns a tuple with the ContactPersonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetContactPersonIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactPersonId.Get(), o.ContactPersonId.IsSet()
}

// HasContactPersonId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasContactPersonId() bool {
	if o != nil && o.ContactPersonId.IsSet() {
		return true
	}

	return false
}

// SetContactPersonId gets a reference to the given NullableInt64 and assigns it to the ContactPersonId field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetContactPersonId(v int64) {
	o.ContactPersonId.Set(&v)
}
// SetContactPersonIdNil sets the value for ContactPersonId to be an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetContactPersonIdNil() {
	o.ContactPersonId.Set(nil)
}

// UnsetContactPersonId ensures that no value is present for ContactPersonId, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) UnsetContactPersonId() {
	o.ContactPersonId.Unset()
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetAdditionalData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) GetAdditionalDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return map[string]interface{}{}, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) HasAdditionalData() bool {
	if o != nil && IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given map[string]interface{} and assigns it to the AdditionalData field.
func (o *IntraService5SettingsApiModelsClientLegalEntityModel62ED) SetAdditionalData(v map[string]interface{}) {
	o.AdditionalData = v
}

func (o IntraService5SettingsApiModelsClientLegalEntityModel62ED) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntraService5SettingsApiModelsClientLegalEntityModel62ED) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.IsArchived) {
		toSerialize["isArchived"] = o.IsArchived
	}
	if o.TimeZoneCode.IsSet() {
		toSerialize["timeZoneCode"] = o.TimeZoneCode.Get()
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.UpdatedBy.IsSet() {
		toSerialize["updatedBy"] = o.UpdatedBy.Get()
	}
	if o.Language.IsSet() {
		toSerialize["language"] = o.Language.Get()
	}
	if o.Address.IsSet() {
		toSerialize["address"] = o.Address.Get()
	}
	if o.Web.IsSet() {
		toSerialize["web"] = o.Web.Get()
	}
	if o.Domains != nil {
		toSerialize["domains"] = o.Domains
	}
	if o.UserGroupTags != nil {
		toSerialize["userGroupTags"] = o.UserGroupTags
	}
	if o.FieldsValues != nil {
		toSerialize["fieldsValues"] = o.FieldsValues
	}
	if o.FieldIdValues != nil {
		toSerialize["fieldIdValues"] = o.FieldIdValues
	}
	if o.ManagerId.IsSet() {
		toSerialize["managerId"] = o.ManagerId.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.TaxpayerNumber.IsSet() {
		toSerialize["taxpayerNumber"] = o.TaxpayerNumber.Get()
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	if o.PhoneNumbersList != nil {
		toSerialize["phoneNumbersList"] = o.PhoneNumbersList
	}
	if o.ContactPersonId.IsSet() {
		toSerialize["contactPersonId"] = o.ContactPersonId.Get()
	}
	if o.AdditionalData != nil {
		toSerialize["additionalData"] = o.AdditionalData
	}
	return toSerialize, nil
}

type NullableIntraService5SettingsApiModelsClientLegalEntityModel62ED struct {
	value *IntraService5SettingsApiModelsClientLegalEntityModel62ED
	isSet bool
}

func (v NullableIntraService5SettingsApiModelsClientLegalEntityModel62ED) Get() *IntraService5SettingsApiModelsClientLegalEntityModel62ED {
	return v.value
}

func (v *NullableIntraService5SettingsApiModelsClientLegalEntityModel62ED) Set(val *IntraService5SettingsApiModelsClientLegalEntityModel62ED) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5SettingsApiModelsClientLegalEntityModel62ED) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5SettingsApiModelsClientLegalEntityModel62ED) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5SettingsApiModelsClientLegalEntityModel62ED(val *IntraService5SettingsApiModelsClientLegalEntityModel62ED) *NullableIntraService5SettingsApiModelsClientLegalEntityModel62ED {
	return &NullableIntraService5SettingsApiModelsClientLegalEntityModel62ED{value: val, isSet: true}
}

func (v NullableIntraService5SettingsApiModelsClientLegalEntityModel62ED) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5SettingsApiModelsClientLegalEntityModel62ED) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


