/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D{}

// IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D struct for IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D
type IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D struct {
	PhoneNumber NullableString `json:"phoneNumber,omitempty"`
	Default *bool `json:"default,omitempty"`
	PhoneExt NullableString `json:"phoneExt,omitempty"`
}

// NewIntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D instantiates a new IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D() *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D {
	this := IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D{}
	return &this
}

// NewIntraService5SharedSqlServerStorageDataModelPhoneNumberValue925DWithDefaults instantiates a new IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntraService5SharedSqlServerStorageDataModelPhoneNumberValue925DWithDefaults() *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D {
	this := IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D{}
	return &this
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber.Get()) {
		var ret string
		return ret
	}
	return *o.PhoneNumber.Get()
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneNumber.Get(), o.PhoneNumber.IsSet()
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber.IsSet() {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given NullableString and assigns it to the PhoneNumber field.
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) SetPhoneNumber(v string) {
	o.PhoneNumber.Set(&v)
}
// SetPhoneNumberNil sets the value for PhoneNumber to be an explicit nil
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) SetPhoneNumberNil() {
	o.PhoneNumber.Set(nil)
}

// UnsetPhoneNumber ensures that no value is present for PhoneNumber, not even an explicit nil
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) UnsetPhoneNumber() {
	o.PhoneNumber.Unset()
}

// GetDefault returns the Default field value if set, zero value otherwise.
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) GetDefault() bool {
	if o == nil || IsNil(o.Default) {
		var ret bool
		return ret
	}
	return *o.Default
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) GetDefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.Default) {
		return nil, false
	}
	return o.Default, true
}

// HasDefault returns a boolean if a field has been set.
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) HasDefault() bool {
	if o != nil && !IsNil(o.Default) {
		return true
	}

	return false
}

// SetDefault gets a reference to the given bool and assigns it to the Default field.
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) SetDefault(v bool) {
	o.Default = &v
}

// GetPhoneExt returns the PhoneExt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) GetPhoneExt() string {
	if o == nil || IsNil(o.PhoneExt.Get()) {
		var ret string
		return ret
	}
	return *o.PhoneExt.Get()
}

// GetPhoneExtOk returns a tuple with the PhoneExt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) GetPhoneExtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PhoneExt.Get(), o.PhoneExt.IsSet()
}

// HasPhoneExt returns a boolean if a field has been set.
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) HasPhoneExt() bool {
	if o != nil && o.PhoneExt.IsSet() {
		return true
	}

	return false
}

// SetPhoneExt gets a reference to the given NullableString and assigns it to the PhoneExt field.
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) SetPhoneExt(v string) {
	o.PhoneExt.Set(&v)
}
// SetPhoneExtNil sets the value for PhoneExt to be an explicit nil
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) SetPhoneExtNil() {
	o.PhoneExt.Set(nil)
}

// UnsetPhoneExt ensures that no value is present for PhoneExt, not even an explicit nil
func (o *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) UnsetPhoneExt() {
	o.PhoneExt.Unset()
}

func (o IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.PhoneNumber.IsSet() {
		toSerialize["phoneNumber"] = o.PhoneNumber.Get()
	}
	if !IsNil(o.Default) {
		toSerialize["default"] = o.Default
	}
	if o.PhoneExt.IsSet() {
		toSerialize["phoneExt"] = o.PhoneExt.Get()
	}
	return toSerialize, nil
}

type NullableIntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D struct {
	value *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D
	isSet bool
}

func (v NullableIntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) Get() *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D {
	return v.value
}

func (v *NullableIntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) Set(val *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D(val *IntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) *NullableIntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D {
	return &NullableIntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D{value: val, isSet: true}
}

func (v NullableIntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5SharedSqlServerStorageDataModelPhoneNumberValue925D) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


