/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// IntraService5SharedEnumsUserTypeE5AC the model 'IntraService5SharedEnumsUserTypeE5AC'
type IntraService5SharedEnumsUserTypeE5AC int32

// List of IntraService5.Shared.Enums.UserType_E5AC
const (
	_10 IntraService5SharedEnumsUserTypeE5AC = 10
	_20 IntraService5SharedEnumsUserTypeE5AC = 20
)

// All allowed values of IntraService5SharedEnumsUserTypeE5AC enum
var AllowedIntraService5SharedEnumsUserTypeE5ACEnumValues = []IntraService5SharedEnumsUserTypeE5AC{
	10,
	20,
}

func (v *IntraService5SharedEnumsUserTypeE5AC) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := IntraService5SharedEnumsUserTypeE5AC(value)
	for _, existing := range AllowedIntraService5SharedEnumsUserTypeE5ACEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid IntraService5SharedEnumsUserTypeE5AC", value)
}

// NewIntraService5SharedEnumsUserTypeE5ACFromValue returns a pointer to a valid IntraService5SharedEnumsUserTypeE5AC
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewIntraService5SharedEnumsUserTypeE5ACFromValue(v int32) (*IntraService5SharedEnumsUserTypeE5AC, error) {
	ev := IntraService5SharedEnumsUserTypeE5AC(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for IntraService5SharedEnumsUserTypeE5AC: valid values are %v", v, AllowedIntraService5SharedEnumsUserTypeE5ACEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v IntraService5SharedEnumsUserTypeE5AC) IsValid() bool {
	for _, existing := range AllowedIntraService5SharedEnumsUserTypeE5ACEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to IntraService5.Shared.Enums.UserType_E5AC value
func (v IntraService5SharedEnumsUserTypeE5AC) Ptr() *IntraService5SharedEnumsUserTypeE5AC {
	return &v
}

type NullableIntraService5SharedEnumsUserTypeE5AC struct {
	value *IntraService5SharedEnumsUserTypeE5AC
	isSet bool
}

func (v NullableIntraService5SharedEnumsUserTypeE5AC) Get() *IntraService5SharedEnumsUserTypeE5AC {
	return v.value
}

func (v *NullableIntraService5SharedEnumsUserTypeE5AC) Set(val *IntraService5SharedEnumsUserTypeE5AC) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5SharedEnumsUserTypeE5AC) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5SharedEnumsUserTypeE5AC) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5SharedEnumsUserTypeE5AC(val *IntraService5SharedEnumsUserTypeE5AC) *NullableIntraService5SharedEnumsUserTypeE5AC {
	return &NullableIntraService5SharedEnumsUserTypeE5AC{value: val, isSet: true}
}

func (v NullableIntraService5SharedEnumsUserTypeE5AC) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5SharedEnumsUserTypeE5AC) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

