/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// IntraService5SharedEnumsClientType6CE9 the model 'IntraService5SharedEnumsClientType6CE9'
type IntraService5SharedEnumsClientType6CE9 int32

// List of IntraService5.Shared.Enums.ClientType_6CE9
const (
	_10 IntraService5SharedEnumsClientType6CE9 = 10
	_20 IntraService5SharedEnumsClientType6CE9 = 20
	_30 IntraService5SharedEnumsClientType6CE9 = 30
)

// All allowed values of IntraService5SharedEnumsClientType6CE9 enum
var AllowedIntraService5SharedEnumsClientType6CE9EnumValues = []IntraService5SharedEnumsClientType6CE9{
	10,
	20,
	30,
}

func (v *IntraService5SharedEnumsClientType6CE9) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := IntraService5SharedEnumsClientType6CE9(value)
	for _, existing := range AllowedIntraService5SharedEnumsClientType6CE9EnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid IntraService5SharedEnumsClientType6CE9", value)
}

// NewIntraService5SharedEnumsClientType6CE9FromValue returns a pointer to a valid IntraService5SharedEnumsClientType6CE9
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewIntraService5SharedEnumsClientType6CE9FromValue(v int32) (*IntraService5SharedEnumsClientType6CE9, error) {
	ev := IntraService5SharedEnumsClientType6CE9(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for IntraService5SharedEnumsClientType6CE9: valid values are %v", v, AllowedIntraService5SharedEnumsClientType6CE9EnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v IntraService5SharedEnumsClientType6CE9) IsValid() bool {
	for _, existing := range AllowedIntraService5SharedEnumsClientType6CE9EnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to IntraService5.Shared.Enums.ClientType_6CE9 value
func (v IntraService5SharedEnumsClientType6CE9) Ptr() *IntraService5SharedEnumsClientType6CE9 {
	return &v
}

type NullableIntraService5SharedEnumsClientType6CE9 struct {
	value *IntraService5SharedEnumsClientType6CE9
	isSet bool
}

func (v NullableIntraService5SharedEnumsClientType6CE9) Get() *IntraService5SharedEnumsClientType6CE9 {
	return v.value
}

func (v *NullableIntraService5SharedEnumsClientType6CE9) Set(val *IntraService5SharedEnumsClientType6CE9) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5SharedEnumsClientType6CE9) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5SharedEnumsClientType6CE9) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5SharedEnumsClientType6CE9(val *IntraService5SharedEnumsClientType6CE9) *NullableIntraService5SharedEnumsClientType6CE9 {
	return &NullableIntraService5SharedEnumsClientType6CE9{value: val, isSet: true}
}

func (v NullableIntraService5SharedEnumsClientType6CE9) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5SharedEnumsClientType6CE9) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

