/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IntraService5SettingsApiModelsUserPhotosB2B1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntraService5SettingsApiModelsUserPhotosB2B1{}

// IntraService5SettingsApiModelsUserPhotosB2B1 struct for IntraService5SettingsApiModelsUserPhotosB2B1
type IntraService5SettingsApiModelsUserPhotosB2B1 struct {
	UserFoto NullableString `json:"userFoto,omitempty"`
	UserThumbnai NullableString `json:"userThumbnai,omitempty"`
}

// NewIntraService5SettingsApiModelsUserPhotosB2B1 instantiates a new IntraService5SettingsApiModelsUserPhotosB2B1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntraService5SettingsApiModelsUserPhotosB2B1() *IntraService5SettingsApiModelsUserPhotosB2B1 {
	this := IntraService5SettingsApiModelsUserPhotosB2B1{}
	return &this
}

// NewIntraService5SettingsApiModelsUserPhotosB2B1WithDefaults instantiates a new IntraService5SettingsApiModelsUserPhotosB2B1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntraService5SettingsApiModelsUserPhotosB2B1WithDefaults() *IntraService5SettingsApiModelsUserPhotosB2B1 {
	this := IntraService5SettingsApiModelsUserPhotosB2B1{}
	return &this
}

// GetUserFoto returns the UserFoto field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsUserPhotosB2B1) GetUserFoto() string {
	if o == nil || IsNil(o.UserFoto.Get()) {
		var ret string
		return ret
	}
	return *o.UserFoto.Get()
}

// GetUserFotoOk returns a tuple with the UserFoto field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsUserPhotosB2B1) GetUserFotoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserFoto.Get(), o.UserFoto.IsSet()
}

// HasUserFoto returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsUserPhotosB2B1) HasUserFoto() bool {
	if o != nil && o.UserFoto.IsSet() {
		return true
	}

	return false
}

// SetUserFoto gets a reference to the given NullableString and assigns it to the UserFoto field.
func (o *IntraService5SettingsApiModelsUserPhotosB2B1) SetUserFoto(v string) {
	o.UserFoto.Set(&v)
}
// SetUserFotoNil sets the value for UserFoto to be an explicit nil
func (o *IntraService5SettingsApiModelsUserPhotosB2B1) SetUserFotoNil() {
	o.UserFoto.Set(nil)
}

// UnsetUserFoto ensures that no value is present for UserFoto, not even an explicit nil
func (o *IntraService5SettingsApiModelsUserPhotosB2B1) UnsetUserFoto() {
	o.UserFoto.Unset()
}

// GetUserThumbnai returns the UserThumbnai field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsUserPhotosB2B1) GetUserThumbnai() string {
	if o == nil || IsNil(o.UserThumbnai.Get()) {
		var ret string
		return ret
	}
	return *o.UserThumbnai.Get()
}

// GetUserThumbnaiOk returns a tuple with the UserThumbnai field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsUserPhotosB2B1) GetUserThumbnaiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserThumbnai.Get(), o.UserThumbnai.IsSet()
}

// HasUserThumbnai returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsUserPhotosB2B1) HasUserThumbnai() bool {
	if o != nil && o.UserThumbnai.IsSet() {
		return true
	}

	return false
}

// SetUserThumbnai gets a reference to the given NullableString and assigns it to the UserThumbnai field.
func (o *IntraService5SettingsApiModelsUserPhotosB2B1) SetUserThumbnai(v string) {
	o.UserThumbnai.Set(&v)
}
// SetUserThumbnaiNil sets the value for UserThumbnai to be an explicit nil
func (o *IntraService5SettingsApiModelsUserPhotosB2B1) SetUserThumbnaiNil() {
	o.UserThumbnai.Set(nil)
}

// UnsetUserThumbnai ensures that no value is present for UserThumbnai, not even an explicit nil
func (o *IntraService5SettingsApiModelsUserPhotosB2B1) UnsetUserThumbnai() {
	o.UserThumbnai.Unset()
}

func (o IntraService5SettingsApiModelsUserPhotosB2B1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntraService5SettingsApiModelsUserPhotosB2B1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.UserFoto.IsSet() {
		toSerialize["userFoto"] = o.UserFoto.Get()
	}
	if o.UserThumbnai.IsSet() {
		toSerialize["userThumbnai"] = o.UserThumbnai.Get()
	}
	return toSerialize, nil
}

type NullableIntraService5SettingsApiModelsUserPhotosB2B1 struct {
	value *IntraService5SettingsApiModelsUserPhotosB2B1
	isSet bool
}

func (v NullableIntraService5SettingsApiModelsUserPhotosB2B1) Get() *IntraService5SettingsApiModelsUserPhotosB2B1 {
	return v.value
}

func (v *NullableIntraService5SettingsApiModelsUserPhotosB2B1) Set(val *IntraService5SettingsApiModelsUserPhotosB2B1) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5SettingsApiModelsUserPhotosB2B1) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5SettingsApiModelsUserPhotosB2B1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5SettingsApiModelsUserPhotosB2B1(val *IntraService5SettingsApiModelsUserPhotosB2B1) *NullableIntraService5SettingsApiModelsUserPhotosB2B1 {
	return &NullableIntraService5SettingsApiModelsUserPhotosB2B1{value: val, isSet: true}
}

func (v NullableIntraService5SettingsApiModelsUserPhotosB2B1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5SettingsApiModelsUserPhotosB2B1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


