/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IntraService5SettingsApiModelsFilterHintModelECE3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntraService5SettingsApiModelsFilterHintModelECE3{}

// IntraService5SettingsApiModelsFilterHintModelECE3 struct for IntraService5SettingsApiModelsFilterHintModelECE3
type IntraService5SettingsApiModelsFilterHintModelECE3 struct {
	Id *int64 `json:"id,omitempty"`
	Value NullableString `json:"value,omitempty"`
	Name NullableString `json:"name,omitempty"`
	IsArchived NullableBool `json:"isArchived,omitempty"`
}

// NewIntraService5SettingsApiModelsFilterHintModelECE3 instantiates a new IntraService5SettingsApiModelsFilterHintModelECE3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntraService5SettingsApiModelsFilterHintModelECE3() *IntraService5SettingsApiModelsFilterHintModelECE3 {
	this := IntraService5SettingsApiModelsFilterHintModelECE3{}
	return &this
}

// NewIntraService5SettingsApiModelsFilterHintModelECE3WithDefaults instantiates a new IntraService5SettingsApiModelsFilterHintModelECE3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntraService5SettingsApiModelsFilterHintModelECE3WithDefaults() *IntraService5SettingsApiModelsFilterHintModelECE3 {
	this := IntraService5SettingsApiModelsFilterHintModelECE3{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) SetId(v int64) {
	o.Id = &v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) GetValue() string {
	if o == nil || IsNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) SetValue(v string) {
	o.Value.Set(&v)
}
// SetValueNil sets the value for Value to be an explicit nil
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) UnsetValue() {
	o.Value.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) UnsetName() {
	o.Name.Unset()
}

// GetIsArchived returns the IsArchived field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) GetIsArchived() bool {
	if o == nil || IsNil(o.IsArchived.Get()) {
		var ret bool
		return ret
	}
	return *o.IsArchived.Get()
}

// GetIsArchivedOk returns a tuple with the IsArchived field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) GetIsArchivedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsArchived.Get(), o.IsArchived.IsSet()
}

// HasIsArchived returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) HasIsArchived() bool {
	if o != nil && o.IsArchived.IsSet() {
		return true
	}

	return false
}

// SetIsArchived gets a reference to the given NullableBool and assigns it to the IsArchived field.
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) SetIsArchived(v bool) {
	o.IsArchived.Set(&v)
}
// SetIsArchivedNil sets the value for IsArchived to be an explicit nil
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) SetIsArchivedNil() {
	o.IsArchived.Set(nil)
}

// UnsetIsArchived ensures that no value is present for IsArchived, not even an explicit nil
func (o *IntraService5SettingsApiModelsFilterHintModelECE3) UnsetIsArchived() {
	o.IsArchived.Unset()
}

func (o IntraService5SettingsApiModelsFilterHintModelECE3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntraService5SettingsApiModelsFilterHintModelECE3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.IsArchived.IsSet() {
		toSerialize["isArchived"] = o.IsArchived.Get()
	}
	return toSerialize, nil
}

type NullableIntraService5SettingsApiModelsFilterHintModelECE3 struct {
	value *IntraService5SettingsApiModelsFilterHintModelECE3
	isSet bool
}

func (v NullableIntraService5SettingsApiModelsFilterHintModelECE3) Get() *IntraService5SettingsApiModelsFilterHintModelECE3 {
	return v.value
}

func (v *NullableIntraService5SettingsApiModelsFilterHintModelECE3) Set(val *IntraService5SettingsApiModelsFilterHintModelECE3) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5SettingsApiModelsFilterHintModelECE3) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5SettingsApiModelsFilterHintModelECE3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5SettingsApiModelsFilterHintModelECE3(val *IntraService5SettingsApiModelsFilterHintModelECE3) *NullableIntraService5SettingsApiModelsFilterHintModelECE3 {
	return &NullableIntraService5SettingsApiModelsFilterHintModelECE3{value: val, isSet: true}
}

func (v NullableIntraService5SettingsApiModelsFilterHintModelECE3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5SettingsApiModelsFilterHintModelECE3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


