/*
Settings API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the IntraService5SettingsApiModelsClientPhysicalPersonModelE777 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntraService5SettingsApiModelsClientPhysicalPersonModelE777{}

// IntraService5SettingsApiModelsClientPhysicalPersonModelE777 struct for IntraService5SettingsApiModelsClientPhysicalPersonModelE777
type IntraService5SettingsApiModelsClientPhysicalPersonModelE777 struct {
	Id *int64 `json:"id,omitempty"`
	Description NullableString `json:"description,omitempty"`
	IsArchived *bool `json:"isArchived,omitempty"`
	TimeZoneCode NullableString `json:"timeZoneCode,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	UpdatedBy NullableString `json:"updatedBy,omitempty"`
	Language NullableString `json:"language,omitempty"`
	Address NullableString `json:"address,omitempty"`
	Web NullableString `json:"web,omitempty"`
	Domains []string `json:"domains,omitempty"`
	UserGroupTags []IntraService5SettingsApiModelsBaseNamedModel10D7 `json:"userGroupTags,omitempty"`
	FieldsValues []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9 `json:"fieldsValues,omitempty"`
	FieldIdValues []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 `json:"fieldIdValues,omitempty"`
	ManagerId NullableInt64 `json:"managerId,omitempty"`
	ContactPersonFirstName NullableString `json:"contactPersonFirstName,omitempty"`
	ContactPersonLastName NullableString `json:"contactPersonLastName,omitempty"`
	ContactPersonMiddleName NullableString `json:"contactPersonMiddleName,omitempty"`
	ContactPersonPassword NullableString `json:"contactPersonPassword,omitempty"`
	ContactPersonRoleId NullableInt64 `json:"contactPersonRoleId,omitempty"`
	ContactPersonEmail NullableString `json:"contactPersonEmail,omitempty"`
	ContactPersonAdditionalEmails []string `json:"contactPersonAdditionalEmails,omitempty"`
	ContactPersonPhoneNumbersList []IntraService5SettingsApiModelsPhoneNumbersListDtoCB78 `json:"contactPersonPhoneNumbersList,omitempty"`
	ContactPersonFieldsValues []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9 `json:"contactPersonFieldsValues,omitempty"`
	ContactPersonFieldIdValues []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 `json:"contactPersonFieldIdValues,omitempty"`
	ContactPersonUserTags []IntraService5SettingsApiModelsBaseNamedModel10D7 `json:"contactPersonUserTags,omitempty"`
	ContactPersonFotoImage NullableString `json:"contactPersonFotoImage,omitempty"`
	ContactPersonIsNewFoto *bool `json:"contactPersonIsNewFoto,omitempty"`
	AdditionalData map[string]interface{} `json:"additionalData,omitempty"`
	ContactPersonId NullableInt64 `json:"contactPersonId,omitempty"`
	EmailConfirmed NullableBool `json:"emailConfirmed,omitempty"`
}

// NewIntraService5SettingsApiModelsClientPhysicalPersonModelE777 instantiates a new IntraService5SettingsApiModelsClientPhysicalPersonModelE777 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntraService5SettingsApiModelsClientPhysicalPersonModelE777() *IntraService5SettingsApiModelsClientPhysicalPersonModelE777 {
	this := IntraService5SettingsApiModelsClientPhysicalPersonModelE777{}
	return &this
}

// NewIntraService5SettingsApiModelsClientPhysicalPersonModelE777WithDefaults instantiates a new IntraService5SettingsApiModelsClientPhysicalPersonModelE777 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntraService5SettingsApiModelsClientPhysicalPersonModelE777WithDefaults() *IntraService5SettingsApiModelsClientPhysicalPersonModelE777 {
	this := IntraService5SettingsApiModelsClientPhysicalPersonModelE777{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetId(v int64) {
	o.Id = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetDescription() {
	o.Description.Unset()
}

// GetIsArchived returns the IsArchived field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetIsArchived() bool {
	if o == nil || IsNil(o.IsArchived) {
		var ret bool
		return ret
	}
	return *o.IsArchived
}

// GetIsArchivedOk returns a tuple with the IsArchived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetIsArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsArchived) {
		return nil, false
	}
	return o.IsArchived, true
}

// HasIsArchived returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasIsArchived() bool {
	if o != nil && !IsNil(o.IsArchived) {
		return true
	}

	return false
}

// SetIsArchived gets a reference to the given bool and assigns it to the IsArchived field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetIsArchived(v bool) {
	o.IsArchived = &v
}

// GetTimeZoneCode returns the TimeZoneCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetTimeZoneCode() string {
	if o == nil || IsNil(o.TimeZoneCode.Get()) {
		var ret string
		return ret
	}
	return *o.TimeZoneCode.Get()
}

// GetTimeZoneCodeOk returns a tuple with the TimeZoneCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetTimeZoneCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimeZoneCode.Get(), o.TimeZoneCode.IsSet()
}

// HasTimeZoneCode returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasTimeZoneCode() bool {
	if o != nil && o.TimeZoneCode.IsSet() {
		return true
	}

	return false
}

// SetTimeZoneCode gets a reference to the given NullableString and assigns it to the TimeZoneCode field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetTimeZoneCode(v string) {
	o.TimeZoneCode.Set(&v)
}
// SetTimeZoneCodeNil sets the value for TimeZoneCode to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetTimeZoneCodeNil() {
	o.TimeZoneCode.Set(nil)
}

// UnsetTimeZoneCode ensures that no value is present for TimeZoneCode, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetTimeZoneCode() {
	o.TimeZoneCode.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetUpdatedBy() string {
	if o == nil || IsNil(o.UpdatedBy.Get()) {
		var ret string
		return ret
	}
	return *o.UpdatedBy.Get()
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetUpdatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UpdatedBy.Get(), o.UpdatedBy.IsSet()
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasUpdatedBy() bool {
	if o != nil && o.UpdatedBy.IsSet() {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given NullableString and assigns it to the UpdatedBy field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetUpdatedBy(v string) {
	o.UpdatedBy.Set(&v)
}
// SetUpdatedByNil sets the value for UpdatedBy to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetUpdatedByNil() {
	o.UpdatedBy.Set(nil)
}

// UnsetUpdatedBy ensures that no value is present for UpdatedBy, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetUpdatedBy() {
	o.UpdatedBy.Unset()
}

// GetLanguage returns the Language field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetLanguage() string {
	if o == nil || IsNil(o.Language.Get()) {
		var ret string
		return ret
	}
	return *o.Language.Get()
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Language.Get(), o.Language.IsSet()
}

// HasLanguage returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasLanguage() bool {
	if o != nil && o.Language.IsSet() {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given NullableString and assigns it to the Language field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetLanguage(v string) {
	o.Language.Set(&v)
}
// SetLanguageNil sets the value for Language to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetLanguageNil() {
	o.Language.Set(nil)
}

// UnsetLanguage ensures that no value is present for Language, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetLanguage() {
	o.Language.Unset()
}

// GetAddress returns the Address field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetAddress() string {
	if o == nil || IsNil(o.Address.Get()) {
		var ret string
		return ret
	}
	return *o.Address.Get()
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Address.Get(), o.Address.IsSet()
}

// HasAddress returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasAddress() bool {
	if o != nil && o.Address.IsSet() {
		return true
	}

	return false
}

// SetAddress gets a reference to the given NullableString and assigns it to the Address field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetAddress(v string) {
	o.Address.Set(&v)
}
// SetAddressNil sets the value for Address to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetAddressNil() {
	o.Address.Set(nil)
}

// UnsetAddress ensures that no value is present for Address, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetAddress() {
	o.Address.Unset()
}

// GetWeb returns the Web field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetWeb() string {
	if o == nil || IsNil(o.Web.Get()) {
		var ret string
		return ret
	}
	return *o.Web.Get()
}

// GetWebOk returns a tuple with the Web field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetWebOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Web.Get(), o.Web.IsSet()
}

// HasWeb returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasWeb() bool {
	if o != nil && o.Web.IsSet() {
		return true
	}

	return false
}

// SetWeb gets a reference to the given NullableString and assigns it to the Web field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetWeb(v string) {
	o.Web.Set(&v)
}
// SetWebNil sets the value for Web to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetWebNil() {
	o.Web.Set(nil)
}

// UnsetWeb ensures that no value is present for Web, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetWeb() {
	o.Web.Unset()
}

// GetDomains returns the Domains field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetDomains() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetDomainsOk() ([]string, bool) {
	if o == nil || IsNil(o.Domains) {
		return nil, false
	}
	return o.Domains, true
}

// HasDomains returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasDomains() bool {
	if o != nil && IsNil(o.Domains) {
		return true
	}

	return false
}

// SetDomains gets a reference to the given []string and assigns it to the Domains field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetDomains(v []string) {
	o.Domains = v
}

// GetUserGroupTags returns the UserGroupTags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetUserGroupTags() []IntraService5SettingsApiModelsBaseNamedModel10D7 {
	if o == nil {
		var ret []IntraService5SettingsApiModelsBaseNamedModel10D7
		return ret
	}
	return o.UserGroupTags
}

// GetUserGroupTagsOk returns a tuple with the UserGroupTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetUserGroupTagsOk() ([]IntraService5SettingsApiModelsBaseNamedModel10D7, bool) {
	if o == nil || IsNil(o.UserGroupTags) {
		return nil, false
	}
	return o.UserGroupTags, true
}

// HasUserGroupTags returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasUserGroupTags() bool {
	if o != nil && IsNil(o.UserGroupTags) {
		return true
	}

	return false
}

// SetUserGroupTags gets a reference to the given []IntraService5SettingsApiModelsBaseNamedModel10D7 and assigns it to the UserGroupTags field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetUserGroupTags(v []IntraService5SettingsApiModelsBaseNamedModel10D7) {
	o.UserGroupTags = v
}

// GetFieldsValues returns the FieldsValues field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetFieldsValues() []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9 {
	if o == nil {
		var ret []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9
		return ret
	}
	return o.FieldsValues
}

// GetFieldsValuesOk returns a tuple with the FieldsValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetFieldsValuesOk() ([]IntraService5SettingsApiModelsAdditionalFieldValueModel86F9, bool) {
	if o == nil || IsNil(o.FieldsValues) {
		return nil, false
	}
	return o.FieldsValues, true
}

// HasFieldsValues returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasFieldsValues() bool {
	if o != nil && IsNil(o.FieldsValues) {
		return true
	}

	return false
}

// SetFieldsValues gets a reference to the given []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9 and assigns it to the FieldsValues field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetFieldsValues(v []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9) {
	o.FieldsValues = v
}

// GetFieldIdValues returns the FieldIdValues field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetFieldIdValues() []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 {
	if o == nil {
		var ret []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7
		return ret
	}
	return o.FieldIdValues
}

// GetFieldIdValuesOk returns a tuple with the FieldIdValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetFieldIdValuesOk() ([]IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7, bool) {
	if o == nil || IsNil(o.FieldIdValues) {
		return nil, false
	}
	return o.FieldIdValues, true
}

// HasFieldIdValues returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasFieldIdValues() bool {
	if o != nil && IsNil(o.FieldIdValues) {
		return true
	}

	return false
}

// SetFieldIdValues gets a reference to the given []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 and assigns it to the FieldIdValues field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetFieldIdValues(v []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) {
	o.FieldIdValues = v
}

// GetManagerId returns the ManagerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetManagerId() int64 {
	if o == nil || IsNil(o.ManagerId.Get()) {
		var ret int64
		return ret
	}
	return *o.ManagerId.Get()
}

// GetManagerIdOk returns a tuple with the ManagerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetManagerIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ManagerId.Get(), o.ManagerId.IsSet()
}

// HasManagerId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasManagerId() bool {
	if o != nil && o.ManagerId.IsSet() {
		return true
	}

	return false
}

// SetManagerId gets a reference to the given NullableInt64 and assigns it to the ManagerId field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetManagerId(v int64) {
	o.ManagerId.Set(&v)
}
// SetManagerIdNil sets the value for ManagerId to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetManagerIdNil() {
	o.ManagerId.Set(nil)
}

// UnsetManagerId ensures that no value is present for ManagerId, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetManagerId() {
	o.ManagerId.Unset()
}

// GetContactPersonFirstName returns the ContactPersonFirstName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonFirstName() string {
	if o == nil || IsNil(o.ContactPersonFirstName.Get()) {
		var ret string
		return ret
	}
	return *o.ContactPersonFirstName.Get()
}

// GetContactPersonFirstNameOk returns a tuple with the ContactPersonFirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactPersonFirstName.Get(), o.ContactPersonFirstName.IsSet()
}

// HasContactPersonFirstName returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasContactPersonFirstName() bool {
	if o != nil && o.ContactPersonFirstName.IsSet() {
		return true
	}

	return false
}

// SetContactPersonFirstName gets a reference to the given NullableString and assigns it to the ContactPersonFirstName field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonFirstName(v string) {
	o.ContactPersonFirstName.Set(&v)
}
// SetContactPersonFirstNameNil sets the value for ContactPersonFirstName to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonFirstNameNil() {
	o.ContactPersonFirstName.Set(nil)
}

// UnsetContactPersonFirstName ensures that no value is present for ContactPersonFirstName, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetContactPersonFirstName() {
	o.ContactPersonFirstName.Unset()
}

// GetContactPersonLastName returns the ContactPersonLastName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonLastName() string {
	if o == nil || IsNil(o.ContactPersonLastName.Get()) {
		var ret string
		return ret
	}
	return *o.ContactPersonLastName.Get()
}

// GetContactPersonLastNameOk returns a tuple with the ContactPersonLastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactPersonLastName.Get(), o.ContactPersonLastName.IsSet()
}

// HasContactPersonLastName returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasContactPersonLastName() bool {
	if o != nil && o.ContactPersonLastName.IsSet() {
		return true
	}

	return false
}

// SetContactPersonLastName gets a reference to the given NullableString and assigns it to the ContactPersonLastName field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonLastName(v string) {
	o.ContactPersonLastName.Set(&v)
}
// SetContactPersonLastNameNil sets the value for ContactPersonLastName to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonLastNameNil() {
	o.ContactPersonLastName.Set(nil)
}

// UnsetContactPersonLastName ensures that no value is present for ContactPersonLastName, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetContactPersonLastName() {
	o.ContactPersonLastName.Unset()
}

// GetContactPersonMiddleName returns the ContactPersonMiddleName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonMiddleName() string {
	if o == nil || IsNil(o.ContactPersonMiddleName.Get()) {
		var ret string
		return ret
	}
	return *o.ContactPersonMiddleName.Get()
}

// GetContactPersonMiddleNameOk returns a tuple with the ContactPersonMiddleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonMiddleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactPersonMiddleName.Get(), o.ContactPersonMiddleName.IsSet()
}

// HasContactPersonMiddleName returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasContactPersonMiddleName() bool {
	if o != nil && o.ContactPersonMiddleName.IsSet() {
		return true
	}

	return false
}

// SetContactPersonMiddleName gets a reference to the given NullableString and assigns it to the ContactPersonMiddleName field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonMiddleName(v string) {
	o.ContactPersonMiddleName.Set(&v)
}
// SetContactPersonMiddleNameNil sets the value for ContactPersonMiddleName to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonMiddleNameNil() {
	o.ContactPersonMiddleName.Set(nil)
}

// UnsetContactPersonMiddleName ensures that no value is present for ContactPersonMiddleName, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetContactPersonMiddleName() {
	o.ContactPersonMiddleName.Unset()
}

// GetContactPersonPassword returns the ContactPersonPassword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonPassword() string {
	if o == nil || IsNil(o.ContactPersonPassword.Get()) {
		var ret string
		return ret
	}
	return *o.ContactPersonPassword.Get()
}

// GetContactPersonPasswordOk returns a tuple with the ContactPersonPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactPersonPassword.Get(), o.ContactPersonPassword.IsSet()
}

// HasContactPersonPassword returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasContactPersonPassword() bool {
	if o != nil && o.ContactPersonPassword.IsSet() {
		return true
	}

	return false
}

// SetContactPersonPassword gets a reference to the given NullableString and assigns it to the ContactPersonPassword field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonPassword(v string) {
	o.ContactPersonPassword.Set(&v)
}
// SetContactPersonPasswordNil sets the value for ContactPersonPassword to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonPasswordNil() {
	o.ContactPersonPassword.Set(nil)
}

// UnsetContactPersonPassword ensures that no value is present for ContactPersonPassword, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetContactPersonPassword() {
	o.ContactPersonPassword.Unset()
}

// GetContactPersonRoleId returns the ContactPersonRoleId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonRoleId() int64 {
	if o == nil || IsNil(o.ContactPersonRoleId.Get()) {
		var ret int64
		return ret
	}
	return *o.ContactPersonRoleId.Get()
}

// GetContactPersonRoleIdOk returns a tuple with the ContactPersonRoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonRoleIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactPersonRoleId.Get(), o.ContactPersonRoleId.IsSet()
}

// HasContactPersonRoleId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasContactPersonRoleId() bool {
	if o != nil && o.ContactPersonRoleId.IsSet() {
		return true
	}

	return false
}

// SetContactPersonRoleId gets a reference to the given NullableInt64 and assigns it to the ContactPersonRoleId field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonRoleId(v int64) {
	o.ContactPersonRoleId.Set(&v)
}
// SetContactPersonRoleIdNil sets the value for ContactPersonRoleId to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonRoleIdNil() {
	o.ContactPersonRoleId.Set(nil)
}

// UnsetContactPersonRoleId ensures that no value is present for ContactPersonRoleId, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetContactPersonRoleId() {
	o.ContactPersonRoleId.Unset()
}

// GetContactPersonEmail returns the ContactPersonEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonEmail() string {
	if o == nil || IsNil(o.ContactPersonEmail.Get()) {
		var ret string
		return ret
	}
	return *o.ContactPersonEmail.Get()
}

// GetContactPersonEmailOk returns a tuple with the ContactPersonEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactPersonEmail.Get(), o.ContactPersonEmail.IsSet()
}

// HasContactPersonEmail returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasContactPersonEmail() bool {
	if o != nil && o.ContactPersonEmail.IsSet() {
		return true
	}

	return false
}

// SetContactPersonEmail gets a reference to the given NullableString and assigns it to the ContactPersonEmail field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonEmail(v string) {
	o.ContactPersonEmail.Set(&v)
}
// SetContactPersonEmailNil sets the value for ContactPersonEmail to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonEmailNil() {
	o.ContactPersonEmail.Set(nil)
}

// UnsetContactPersonEmail ensures that no value is present for ContactPersonEmail, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetContactPersonEmail() {
	o.ContactPersonEmail.Unset()
}

// GetContactPersonAdditionalEmails returns the ContactPersonAdditionalEmails field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonAdditionalEmails() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ContactPersonAdditionalEmails
}

// GetContactPersonAdditionalEmailsOk returns a tuple with the ContactPersonAdditionalEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonAdditionalEmailsOk() ([]string, bool) {
	if o == nil || IsNil(o.ContactPersonAdditionalEmails) {
		return nil, false
	}
	return o.ContactPersonAdditionalEmails, true
}

// HasContactPersonAdditionalEmails returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasContactPersonAdditionalEmails() bool {
	if o != nil && IsNil(o.ContactPersonAdditionalEmails) {
		return true
	}

	return false
}

// SetContactPersonAdditionalEmails gets a reference to the given []string and assigns it to the ContactPersonAdditionalEmails field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonAdditionalEmails(v []string) {
	o.ContactPersonAdditionalEmails = v
}

// GetContactPersonPhoneNumbersList returns the ContactPersonPhoneNumbersList field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonPhoneNumbersList() []IntraService5SettingsApiModelsPhoneNumbersListDtoCB78 {
	if o == nil {
		var ret []IntraService5SettingsApiModelsPhoneNumbersListDtoCB78
		return ret
	}
	return o.ContactPersonPhoneNumbersList
}

// GetContactPersonPhoneNumbersListOk returns a tuple with the ContactPersonPhoneNumbersList field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonPhoneNumbersListOk() ([]IntraService5SettingsApiModelsPhoneNumbersListDtoCB78, bool) {
	if o == nil || IsNil(o.ContactPersonPhoneNumbersList) {
		return nil, false
	}
	return o.ContactPersonPhoneNumbersList, true
}

// HasContactPersonPhoneNumbersList returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasContactPersonPhoneNumbersList() bool {
	if o != nil && IsNil(o.ContactPersonPhoneNumbersList) {
		return true
	}

	return false
}

// SetContactPersonPhoneNumbersList gets a reference to the given []IntraService5SettingsApiModelsPhoneNumbersListDtoCB78 and assigns it to the ContactPersonPhoneNumbersList field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonPhoneNumbersList(v []IntraService5SettingsApiModelsPhoneNumbersListDtoCB78) {
	o.ContactPersonPhoneNumbersList = v
}

// GetContactPersonFieldsValues returns the ContactPersonFieldsValues field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonFieldsValues() []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9 {
	if o == nil {
		var ret []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9
		return ret
	}
	return o.ContactPersonFieldsValues
}

// GetContactPersonFieldsValuesOk returns a tuple with the ContactPersonFieldsValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonFieldsValuesOk() ([]IntraService5SettingsApiModelsAdditionalFieldValueModel86F9, bool) {
	if o == nil || IsNil(o.ContactPersonFieldsValues) {
		return nil, false
	}
	return o.ContactPersonFieldsValues, true
}

// HasContactPersonFieldsValues returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasContactPersonFieldsValues() bool {
	if o != nil && IsNil(o.ContactPersonFieldsValues) {
		return true
	}

	return false
}

// SetContactPersonFieldsValues gets a reference to the given []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9 and assigns it to the ContactPersonFieldsValues field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonFieldsValues(v []IntraService5SettingsApiModelsAdditionalFieldValueModel86F9) {
	o.ContactPersonFieldsValues = v
}

// GetContactPersonFieldIdValues returns the ContactPersonFieldIdValues field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonFieldIdValues() []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 {
	if o == nil {
		var ret []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7
		return ret
	}
	return o.ContactPersonFieldIdValues
}

// GetContactPersonFieldIdValuesOk returns a tuple with the ContactPersonFieldIdValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonFieldIdValuesOk() ([]IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7, bool) {
	if o == nil || IsNil(o.ContactPersonFieldIdValues) {
		return nil, false
	}
	return o.ContactPersonFieldIdValues, true
}

// HasContactPersonFieldIdValues returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasContactPersonFieldIdValues() bool {
	if o != nil && IsNil(o.ContactPersonFieldIdValues) {
		return true
	}

	return false
}

// SetContactPersonFieldIdValues gets a reference to the given []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7 and assigns it to the ContactPersonFieldIdValues field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonFieldIdValues(v []IntraService5SettingsApiModelsAdditionalFieldIdValueModel15E7) {
	o.ContactPersonFieldIdValues = v
}

// GetContactPersonUserTags returns the ContactPersonUserTags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonUserTags() []IntraService5SettingsApiModelsBaseNamedModel10D7 {
	if o == nil {
		var ret []IntraService5SettingsApiModelsBaseNamedModel10D7
		return ret
	}
	return o.ContactPersonUserTags
}

// GetContactPersonUserTagsOk returns a tuple with the ContactPersonUserTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonUserTagsOk() ([]IntraService5SettingsApiModelsBaseNamedModel10D7, bool) {
	if o == nil || IsNil(o.ContactPersonUserTags) {
		return nil, false
	}
	return o.ContactPersonUserTags, true
}

// HasContactPersonUserTags returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasContactPersonUserTags() bool {
	if o != nil && IsNil(o.ContactPersonUserTags) {
		return true
	}

	return false
}

// SetContactPersonUserTags gets a reference to the given []IntraService5SettingsApiModelsBaseNamedModel10D7 and assigns it to the ContactPersonUserTags field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonUserTags(v []IntraService5SettingsApiModelsBaseNamedModel10D7) {
	o.ContactPersonUserTags = v
}

// GetContactPersonFotoImage returns the ContactPersonFotoImage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonFotoImage() string {
	if o == nil || IsNil(o.ContactPersonFotoImage.Get()) {
		var ret string
		return ret
	}
	return *o.ContactPersonFotoImage.Get()
}

// GetContactPersonFotoImageOk returns a tuple with the ContactPersonFotoImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonFotoImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactPersonFotoImage.Get(), o.ContactPersonFotoImage.IsSet()
}

// HasContactPersonFotoImage returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasContactPersonFotoImage() bool {
	if o != nil && o.ContactPersonFotoImage.IsSet() {
		return true
	}

	return false
}

// SetContactPersonFotoImage gets a reference to the given NullableString and assigns it to the ContactPersonFotoImage field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonFotoImage(v string) {
	o.ContactPersonFotoImage.Set(&v)
}
// SetContactPersonFotoImageNil sets the value for ContactPersonFotoImage to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonFotoImageNil() {
	o.ContactPersonFotoImage.Set(nil)
}

// UnsetContactPersonFotoImage ensures that no value is present for ContactPersonFotoImage, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetContactPersonFotoImage() {
	o.ContactPersonFotoImage.Unset()
}

// GetContactPersonIsNewFoto returns the ContactPersonIsNewFoto field value if set, zero value otherwise.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonIsNewFoto() bool {
	if o == nil || IsNil(o.ContactPersonIsNewFoto) {
		var ret bool
		return ret
	}
	return *o.ContactPersonIsNewFoto
}

// GetContactPersonIsNewFotoOk returns a tuple with the ContactPersonIsNewFoto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonIsNewFotoOk() (*bool, bool) {
	if o == nil || IsNil(o.ContactPersonIsNewFoto) {
		return nil, false
	}
	return o.ContactPersonIsNewFoto, true
}

// HasContactPersonIsNewFoto returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasContactPersonIsNewFoto() bool {
	if o != nil && !IsNil(o.ContactPersonIsNewFoto) {
		return true
	}

	return false
}

// SetContactPersonIsNewFoto gets a reference to the given bool and assigns it to the ContactPersonIsNewFoto field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonIsNewFoto(v bool) {
	o.ContactPersonIsNewFoto = &v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetAdditionalData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetAdditionalDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return map[string]interface{}{}, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasAdditionalData() bool {
	if o != nil && IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given map[string]interface{} and assigns it to the AdditionalData field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetAdditionalData(v map[string]interface{}) {
	o.AdditionalData = v
}

// GetContactPersonId returns the ContactPersonId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonId() int64 {
	if o == nil || IsNil(o.ContactPersonId.Get()) {
		var ret int64
		return ret
	}
	return *o.ContactPersonId.Get()
}

// GetContactPersonIdOk returns a tuple with the ContactPersonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetContactPersonIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactPersonId.Get(), o.ContactPersonId.IsSet()
}

// HasContactPersonId returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasContactPersonId() bool {
	if o != nil && o.ContactPersonId.IsSet() {
		return true
	}

	return false
}

// SetContactPersonId gets a reference to the given NullableInt64 and assigns it to the ContactPersonId field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonId(v int64) {
	o.ContactPersonId.Set(&v)
}
// SetContactPersonIdNil sets the value for ContactPersonId to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetContactPersonIdNil() {
	o.ContactPersonId.Set(nil)
}

// UnsetContactPersonId ensures that no value is present for ContactPersonId, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetContactPersonId() {
	o.ContactPersonId.Unset()
}

// GetEmailConfirmed returns the EmailConfirmed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetEmailConfirmed() bool {
	if o == nil || IsNil(o.EmailConfirmed.Get()) {
		var ret bool
		return ret
	}
	return *o.EmailConfirmed.Get()
}

// GetEmailConfirmedOk returns a tuple with the EmailConfirmed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) GetEmailConfirmedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.EmailConfirmed.Get(), o.EmailConfirmed.IsSet()
}

// HasEmailConfirmed returns a boolean if a field has been set.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) HasEmailConfirmed() bool {
	if o != nil && o.EmailConfirmed.IsSet() {
		return true
	}

	return false
}

// SetEmailConfirmed gets a reference to the given NullableBool and assigns it to the EmailConfirmed field.
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetEmailConfirmed(v bool) {
	o.EmailConfirmed.Set(&v)
}
// SetEmailConfirmedNil sets the value for EmailConfirmed to be an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) SetEmailConfirmedNil() {
	o.EmailConfirmed.Set(nil)
}

// UnsetEmailConfirmed ensures that no value is present for EmailConfirmed, not even an explicit nil
func (o *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnsetEmailConfirmed() {
	o.EmailConfirmed.Unset()
}

func (o IntraService5SettingsApiModelsClientPhysicalPersonModelE777) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntraService5SettingsApiModelsClientPhysicalPersonModelE777) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.IsArchived) {
		toSerialize["isArchived"] = o.IsArchived
	}
	if o.TimeZoneCode.IsSet() {
		toSerialize["timeZoneCode"] = o.TimeZoneCode.Get()
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.UpdatedBy.IsSet() {
		toSerialize["updatedBy"] = o.UpdatedBy.Get()
	}
	if o.Language.IsSet() {
		toSerialize["language"] = o.Language.Get()
	}
	if o.Address.IsSet() {
		toSerialize["address"] = o.Address.Get()
	}
	if o.Web.IsSet() {
		toSerialize["web"] = o.Web.Get()
	}
	if o.Domains != nil {
		toSerialize["domains"] = o.Domains
	}
	if o.UserGroupTags != nil {
		toSerialize["userGroupTags"] = o.UserGroupTags
	}
	if o.FieldsValues != nil {
		toSerialize["fieldsValues"] = o.FieldsValues
	}
	if o.FieldIdValues != nil {
		toSerialize["fieldIdValues"] = o.FieldIdValues
	}
	if o.ManagerId.IsSet() {
		toSerialize["managerId"] = o.ManagerId.Get()
	}
	if o.ContactPersonFirstName.IsSet() {
		toSerialize["contactPersonFirstName"] = o.ContactPersonFirstName.Get()
	}
	if o.ContactPersonLastName.IsSet() {
		toSerialize["contactPersonLastName"] = o.ContactPersonLastName.Get()
	}
	if o.ContactPersonMiddleName.IsSet() {
		toSerialize["contactPersonMiddleName"] = o.ContactPersonMiddleName.Get()
	}
	if o.ContactPersonPassword.IsSet() {
		toSerialize["contactPersonPassword"] = o.ContactPersonPassword.Get()
	}
	if o.ContactPersonRoleId.IsSet() {
		toSerialize["contactPersonRoleId"] = o.ContactPersonRoleId.Get()
	}
	if o.ContactPersonEmail.IsSet() {
		toSerialize["contactPersonEmail"] = o.ContactPersonEmail.Get()
	}
	if o.ContactPersonAdditionalEmails != nil {
		toSerialize["contactPersonAdditionalEmails"] = o.ContactPersonAdditionalEmails
	}
	if o.ContactPersonPhoneNumbersList != nil {
		toSerialize["contactPersonPhoneNumbersList"] = o.ContactPersonPhoneNumbersList
	}
	if o.ContactPersonFieldsValues != nil {
		toSerialize["contactPersonFieldsValues"] = o.ContactPersonFieldsValues
	}
	if o.ContactPersonFieldIdValues != nil {
		toSerialize["contactPersonFieldIdValues"] = o.ContactPersonFieldIdValues
	}
	if o.ContactPersonUserTags != nil {
		toSerialize["contactPersonUserTags"] = o.ContactPersonUserTags
	}
	if o.ContactPersonFotoImage.IsSet() {
		toSerialize["contactPersonFotoImage"] = o.ContactPersonFotoImage.Get()
	}
	if !IsNil(o.ContactPersonIsNewFoto) {
		toSerialize["contactPersonIsNewFoto"] = o.ContactPersonIsNewFoto
	}
	if o.AdditionalData != nil {
		toSerialize["additionalData"] = o.AdditionalData
	}
	if o.ContactPersonId.IsSet() {
		toSerialize["contactPersonId"] = o.ContactPersonId.Get()
	}
	if o.EmailConfirmed.IsSet() {
		toSerialize["emailConfirmed"] = o.EmailConfirmed.Get()
	}
	return toSerialize, nil
}

type NullableIntraService5SettingsApiModelsClientPhysicalPersonModelE777 struct {
	value *IntraService5SettingsApiModelsClientPhysicalPersonModelE777
	isSet bool
}

func (v NullableIntraService5SettingsApiModelsClientPhysicalPersonModelE777) Get() *IntraService5SettingsApiModelsClientPhysicalPersonModelE777 {
	return v.value
}

func (v *NullableIntraService5SettingsApiModelsClientPhysicalPersonModelE777) Set(val *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) {
	v.value = val
	v.isSet = true
}

func (v NullableIntraService5SettingsApiModelsClientPhysicalPersonModelE777) IsSet() bool {
	return v.isSet
}

func (v *NullableIntraService5SettingsApiModelsClientPhysicalPersonModelE777) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntraService5SettingsApiModelsClientPhysicalPersonModelE777(val *IntraService5SettingsApiModelsClientPhysicalPersonModelE777) *NullableIntraService5SettingsApiModelsClientPhysicalPersonModelE777 {
	return &NullableIntraService5SettingsApiModelsClientPhysicalPersonModelE777{value: val, isSet: true}
}

func (v NullableIntraService5SettingsApiModelsClientPhysicalPersonModelE777) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntraService5SettingsApiModelsClientPhysicalPersonModelE777) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


